import gncpy.filters
import numpy as np
import numpy.linalg as la
import numpy.random as rnd
import matplotlib.pyplot as plt
from typing import Iterable
from matplotlib.patches import Ellipse
import matplotlib.animation as animation
import abc
from copy import deepcopy
import warnings
import itertools

from carbs.utilities.graphs import (
    k_shortest,
    murty_m_best,
    murty_m_best_all_meas_assigned,
)
from carbs.utilities.sampling import gibbs, mm_gibbs

from gncpy.math import log_sum_exp, get_elem_sym_fnc
import gncpy.plotting as pltUtil
import gncpy.filters as gfilts
import gncpy.errors as gerr

import serums.models as smodels
from serums.enums import SingleObjectDistance
from serums.distances import calculate_ospa, calculate_ospa2, calculate_gospa



### MIGHT HAVE TO CHANGE IMPORTS BELOW, AND THEN CHANGE THEIR NAMES IN THE CLASS?? Depends if we do import serums.models or import GGIWMixture ###

from carbs.swarm_estimator.tracker import RandomFiniteSetBase 
from carbs.extended_targets.GGIW_Serums_Models import GGIWMixture
from carbs.extended_targets.GGIW_Serums_Models import GGIW 
from carbs.extended_targets.gaussKLDiff import gauss_KL_diff
from carbs.extended_targets.iwKLDiff import iw_KL_diff
from carbs.extended_targets.gammaKLDiff import gamma_KL_diff
from carbs.extended_targets.ggiwMerge import ggiw_merge

class GGIW_PHD(RandomFiniteSetBase):
    """Implements the Probability Hypothesis Density filter for the Gamma Gaussian Inverse Wishart distribution.

    The kwargs in the constructor are passed through to the parent constructor.

    Notes
    -----
    The filter implementation is based on :cite:`Vo2006_TheGaussianMixtureProbabilityHypothesisDensityFilter`

    Attributes
    ----------
    gating_on : bool
        flag indicating if measurement gating should be performed. The
        default is False.
    inv_chi2_gate : float
        threshold for the chi squared test in the measurement gating. The
        default is 0.
    extract_threshold : float
        threshold for extracting the state. The default is 0.5.
    prune_threshold : float
        threshold for removing hypotheses. The default is 10**-5.
    merge_threshold : float
        threshold for merging hypotheses. The default is 4.
    max_terms : int
        max number of gaussians to use. The default is 100.

    """

    def __init__(
        self,
        clustering_obj,
        gating_on=False,
        inv_chi2_gate=0,
        extract_threshold=0.5,
        prune_threshold=1e-5,
        merge_threshold=4,
        max_terms=100,
        partition_thresh = 1,
        **kwargs,
    ):
        self.gating_on = gating_on
        self.inv_chi2_gate = inv_chi2_gate
        self.extract_threshold = extract_threshold
        self.prune_threshold = prune_threshold
        self.merge_threshold = merge_threshold
        self.max_terms = max_terms
        self.partition_thresh = partition_thresh

        if clustering_obj is None:
            raise("Please choose a clustering_obj. ")
        else:
            self._clustering_obj = clustering_obj

        self._Mixture = GGIWMixture()


        self.merge_as_average = True    # User can set to true, better numerical stability


        super().__init__(**kwargs)

    def save_filter_state(self):
        """Saves filter variables so they can be restored later."""
        filt_state = super().save_filter_state()

        raise RuntimeError("Not implmented yet")
        return filt_state

    def load_filter_state(self, filt_state):
        """Initializes filter using saved filter state.

        Attributes
        ----------
        filt_state : dict
            Dictionary generated by :meth:`save_filter_state`.
        """
        super().load_filter_state(filt_state)

        raise RuntimeError("Not implmented yet")

    @property
    def states(self):
        """Read only list of extracted states.

        This is a list with 1 element per timestep, and each element is a list
        of the best states extracted at that timestep. The order of each
        element corresponds to the label order.
        """
        if len(self._states) > 0:
            return self._states[-1]
        else:
            return []

    @property
    def covariances(self):
        """Read only list of extracted covariances.

        This is a list with 1 element per timestep, and each element is a list
        of the best covariances extracted at that timestep. The order of each
        element corresponds to the state order.

        Warns
        -----
            RuntimeWarning
                If the class is not saving the covariances, and returns an
                empty list
        """
        if not self.save_covs:
            warnings.warn("Not saving covariances")
            return []
        if len(self._covs) > 0:
            return self._covs[-1]
        else:
            return []

    @property
    def cardinality(self):
        """Read only cardinality of the RFS."""
        if len(self._Mixture) == 0:
            return 0
        else:
            return len(self._Mixture[-1])

    # def _gen_spawned_targets(self, Mixture):
    #     if self.spawn_cov is not None and self.spawn_weight is not None:
    #         gauss_list = [
    #             smodels.Gaussian(mean=m.copy(), covariance=self.spawn_cov.copy())
    #             for m in Mixture.means
    #         ]
    #         return smodels.GaussianMixture(
    #             distributions=gauss_list,
    #             weights=[self.spawn_weight for ii in range(len(gauss_list))],
    #         )
    #     else:
    #         raise RuntimeError(
    #             "self.spawn_cov and self.spawn_weight must be specified."
    #         )

    def test_set_mixture(self, mixture:GGIWMixture) -> None:
        # Function used to overwrite object mixture data. ONLY FOR TESTING
        self._Mixture = mixture

    def predict(self, timestep, filt_args={}):
        """Prediction step of the PHD filter.

        This predicts new hypothesis, and propogates them to the next time
        step. It also updates the cardinality distribution. Because this calls
        the inner filter's predict function, the keyword arguments must contain
        any information needed by that function.


        Parameters
        ----------
        timestep: float
            current timestep
        filt_args : dict, optional
            Passed to the inner filter. The default is {}.

        Returns
        -------
        None.

        """

        if self.enable_spawning:
            print("Warning: Spawning not implemented yet. \n\n")

        # if self.enable_spawning:
        #     spawn_mix = self._gen_spawned_targets(self._Mixture) 
        
        # if self.enable_spawning:
        #     self._Mixture.add_components(
        #         spawn_mix.means, spawn_mix.covariances, spawn_mix.weights
        #     )

        for mix in self.birth_terms:
            obj = mix[1]
            weight = mix[0] 
            self._Mixture.add_components(obj.alpha, obj.beta, obj.mean, obj.covariance, obj.IWdof, obj.IWshape, weight)

        self._Mixture = self._predict_prob_density(timestep, self._Mixture, filt_args)


    def _predict_prob_density(self, timestep, probDensity, filt_args):

        weights = [self.prob_survive * x for x in probDensity.weights.copy()] 
        #print(probDensity.weights.copy())
        n_terms = len(weights)
        NewMixture = GGIWMixture() 
        for ii, _ in enumerate(probDensity._distributions):
            cur_probDensity = probDensity._distributions[ii]
            pred_probDensity = self.filter.predict(timestep,cur_probDensity, filt_args)
            NewMixture.add_components(pred_probDensity.alpha, pred_probDensity.beta, pred_probDensity.mean, pred_probDensity.covariance, pred_probDensity.IWdof, pred_probDensity.IWshape, weights=weights[ii])            
            

        return NewMixture 

    def correct(
        self, timestep, meas_in, meas_mat_args={}, est_meas_args={}, filt_args={}
    ):

        meas = deepcopy(meas_in)

        if self.gating_on:
            print("Warning: gating not implemented yet. \n\n")
            # meas = self._gate_meas(
            #     meas,
            #     self._Mixture.means,
            #     self._Mixture.covariances,
            #     meas_mat_args,
            #     est_meas_args,
            # )

        self._meas_tab.append(meas)   # Keeps track of measurements for plotting purposes

        # Partition measurements
        self._parted_meas = self._clustering_obj.cluster(meas)

        # Mix = GGIWMixture()

        Mix = deepcopy(self._Mixture)

        w_lst = Mix.weights

        # This loop is based on the assumption that any target in the frame must have at least one measurement, gets rid of weird bugs at low PD
        for ii, x in enumerate(Mix):
            if x not in self.birth_terms:
                w_lst[ii] = w_lst[ii]*self.prob_miss_detection

        Mix.weights = w_lst

        UpdMix = self._correct_prob_density(timestep, self._parted_meas, self._Mixture, filt_args) 
        UpdMix.add_components(Mix.alphas, Mix.betas, Mix.means, Mix.covariances, Mix.IWdofs, Mix.IWshapes, Mix.weights) 

        self._Mixture = UpdMix

    def _correct_prob_density(self, timestep, parted_meas, probDensity, filt_args):
        # means = []
        # covariances = []

        weights = []

        Mix_temp = GGIWMixture()

        # det_weights = [self.prob_detection * x for x in probDensity.weights]

        a_lst = probDensity.alphas
        b_lst = probDensity.betas
        w_lst = probDensity.weights

        det_weights = [self.prob_detection * weight for ii, weight in enumerate(w_lst)] # [self.prob_detection * (b_lst[ii] / (1 + b_lst[ii])) ** a_lst[ii] * weight for ii, weight in enumerate(w_lst)]

        for z in parted_meas: 

            w_lst = []
            # a_lst = []
            # b_lst = []
            # m_lst = []
            # P_lst = []
            # v_lst = []
            # V_lst = []

            # Convert the measurement set from list of len N of Dx1 arrays to 
            # an DxN array 
            num_meas = len(z)
            meas_d = z[0].shape[0]
            z_array = np.array(z).reshape((num_meas, meas_d)).transpose()

            for jj in range(0, len(probDensity)):
                cur_dist = probDensity[jj] 
                (upd_dist, qz) = self.filter.correct(timestep, z_array, cur_dist, **filt_args) 
                w = np.exp(qz) * det_weights[jj]

                # a_lst.append(upd_dist.alpha)
                # b_lst.append(upd_dist.beta)
                # m_lst.append(upd_dist.mean)
                # P_lst.append(upd_dist.covariance)
                # v_lst.append(upd_dist.IWdof)
                # V_lst.append(upd_dist.IWshape)

                Mix_temp.add_components(upd_dist.alpha, upd_dist.beta, upd_dist.mean, upd_dist.covariance, upd_dist.IWdof, upd_dist.IWshape, w)            

                w_lst.append(w)

            weights.extend(
                [x / (self.clutter_rate * self.clutter_den + sum(w_lst)) for x in w_lst]
            )

        Mix_temp.weights = weights

        return Mix_temp
        # return GGIWMixture(alphas=a_lst,betas=b_lst,means=m_lst,covariances=P_lst,IWdofs=v_lst,IWshapes=V_lst,weights=weights)

    def _prune(self):
        """Removes hypotheses below a threshold.

        This should be called once per time step after the correction and
        before the state extraction.
        """
        inds = np.where(np.asarray(self._Mixture.weights) < self.prune_threshold)[0]
        self._Mixture.remove_components(inds.flatten().tolist())
        return inds

    def _merge(self):
            """Merges nearby hypotheses."""
            loop_inds = set(range(len(self._Mixture.means)))
            if len(loop_inds) < 2:
                # Exit if num component is less than 2
                return

            if self.merge_as_average:
                loop_inds = set(range(len(self._Mixture.means)))
                
                w_lst = []
                a_lst = []
                b_lst = []
                m_lst = []
                p_lst = []
                v_lst = []
                V_lst = []
                
                while loop_inds:
                    remaining_weights = {i: self._Mixture.weights[i] for i in loop_inds}
                    jj = max(remaining_weights, key=remaining_weights.get)
                    
                    comp_inds = set()
                    inv_cov = la.inv(self._Mixture.covariances[jj])
                    
                    for ii in loop_inds:
                        diff = self._Mixture.means[ii] - self._Mixture.means[jj]
                        val = diff.T @ inv_cov @ diff
                        if val <= self.merge_threshold:
                            comp_inds.add(ii)
                    
                    w_new = sum([self._Mixture.weights[ii] for ii in comp_inds])
                    
                    if w_new <= 0:
                        loop_inds = loop_inds.difference(comp_inds)
                        continue
                        
                    m_new = sum([self._Mixture.weights[ii] * self._Mixture.means[ii] for ii in comp_inds]) / w_new
                    
                    p_new = sum([self._Mixture.weights[ii] * self._Mixture.covariances[ii] for ii in comp_inds]) / w_new
                    p_new = 0.5 * (p_new + p_new.T) 
                    
                    a_new = sum([self._Mixture.weights[ii] * self._Mixture.alphas[ii] for ii in comp_inds]) / w_new
                    
                    b_new = sum([self._Mixture.weights[ii] * self._Mixture.betas[ii] for ii in comp_inds]) / w_new
                    
                    v_new = sum([self._Mixture.weights[ii] * self._Mixture.IWdofs[ii] for ii in comp_inds]) / w_new
                    
                    V_new = sum([self._Mixture.weights[ii] * self._Mixture.IWshapes[ii] for ii in comp_inds]) / w_new
                    
                    w_lst.append(w_new)
                    m_lst.append(m_new)
                    p_lst.append(p_new)
                    a_lst.append(a_new)
                    b_lst.append(b_new)
                    v_lst.append(v_new)
                    V_lst.append(V_new)
                    
                    loop_inds = loop_inds.difference(comp_inds)
                
                self._Mixture = GGIWMixture(
                    alphas=a_lst,
                    betas=b_lst,
                    means=m_lst,
                    covariances=p_lst,
                    IWdofs=v_lst,
                    IWshapes=V_lst,
                    weights=w_lst
                )
            else:
                loop_inds = set(range(len(self._Mixture.means)))
                
                new_mixture = GGIWMixture()

                # Calculate the KL difference matrix of component distribution
                gauss_dist = gauss_KL_diff(self._Mixture.means, self._Mixture.covariances)
                iw_dist = iw_KL_diff(self._Mixture.IWdofs, self._Mixture.IWshapes)
                gamma_dist = gamma_KL_diff(self._Mixture.alphas, self._Mixture.betas)

                tot_dist = gauss_dist + iw_dist + gamma_dist
                
                while len(loop_inds) > 0:
                    jj = int(np.argmax(self._Mixture.weights))

                    comp_ind = []
                    for ii in loop_inds:
                        if tot_dist[jj,ii] <= self.merge_threshold:
                            comp_ind.append(ii)
                    cluster_weight = [self._Mixture.weights[ii] for ii in comp_ind]
                    cluster_mean =  [self._Mixture.means[ii] for ii in comp_ind]
                    cluster_cov =  [self._Mixture.covariances[ii] for ii in comp_ind]
                    cluster_alpha =  [self._Mixture.alphas[ii] for ii in comp_ind]
                    cluster_beta =  [self._Mixture.betas[ii] for ii in comp_ind]
                    cluster_iwdof =  [self._Mixture.IWdofs[ii] for ii in comp_ind]
                    cluster_iwshape = [self._Mixture.IWshapes[ii] for ii in comp_ind]

                    w_merged, ggiw_merged = ggiw_merge(w=cluster_weight, means=cluster_mean, \
                                                    covs = cluster_cov, alphas= cluster_alpha, \
                                                        betas = cluster_beta, IWdof=cluster_iwdof, \
                                                            IWshape=cluster_iwshape, opt_alpha=True, opt_nu=True)
                    new_mixture.add_components(weights=w_merged, ggiw=ggiw_merged)
                    
                    loop_inds = loop_inds.symmetric_difference(comp_ind)
                    for ii in comp_ind:
                        self._Mixture.weights[ii] = -1
                
                self._Mixture = new_mixture

    def _cap(self):
        """Removes least likely hypotheses until a maximum number is reached.

        This should be called once per time step after pruning and
        before the state extraction.
        """
        if len(self._Mixture.weights) > self.max_terms:
            idx = np.argsort(self._Mixture.weights)
            w = sum(self._Mixture.weights)
            self._Mixture.remove_components(idx[0 : -self.max_terms])
            self._Mixture.weights = [
                x * (w / sum(self._Mixture.weights)) for x in self._Mixture.weights
            ]
            return idx[0 : -self.max_terms].tolist()

    def extract_states(self):
        """Extracts the best state estimates.

        This extracts the best states from the distribution. It should be
        called once per time step after the correction function.
        """
        inds = np.where(np.asarray(self._Mixture.weights) >= self.extract_threshold)
        inds = np.ndarray.flatten(inds[0])
        s_lst = []
        c_lst = []
        for jj in inds:
            jj = int(jj)
            num_reps = round(self._Mixture.weights[jj])
            s_lst.extend([self._Mixture.means[jj]] * num_reps)
            if self.save_covs:
                c_lst.extend([self._Mixture.covariances[jj]] * num_reps)
        self._states.append(s_lst)
        if self.save_covs:
            self._covs.append(c_lst)

    def extract_mixture(self): 
        inds = np.where(np.asarray(self._Mixture.weights) >= self.extract_threshold)[0]

        temp = GGIWMixture() 

        for ii in inds:
            mix = self._Mixture[int(ii)]
            temp.add_components(
                mix.alpha,
                mix.beta,
                mix.mean,
                mix.covariance,
                mix.IWdof,
                mix.IWshape,
                self._Mixture.weights[ii]
            )

        return temp

    def cleanup(
        self,
        enable_prune=True,
        enable_cap=True,
        enable_merge=True,
        enable_extract=True,
        extract_kwargs=None,
    ):
        """Performs the cleanup step of the filter.

        This can prune, cap, and extract states. It must be called once per
        timestep. If this is called with `enable_extract` set to true then
        the extract states method does not need to be called separately. It is
        recommended to call this function instead of
        :meth:`carbs.swarm_estimator.tracker.GeneralizedLabeledMultiBernoulli.extract_states`
        directly.

        Parameters
        ----------
        enable_prune : bool, optional
            Flag indicating if prunning should be performed. The default is True.
        enable_cap : bool, optional
            Flag indicating if capping should be performed. The default is True.
        enable_merge : bool, optional
            Flag indicating if merging should be performed. The default is True.
        enable_extract : bool, optional
            Flag indicating if state extraction should be performed. The default is True.
        extract_kwargs : dict, optional
            Extra arguments to pass to the extract function.
        """
        if enable_prune:
            self._prune()
        if enable_merge:
            self._merge()
        if enable_cap:
            self._cap()
        if enable_extract:
            if extract_kwargs is None:
                extract_kwargs = {}
            self.extract_states(**extract_kwargs)

    def __ani_state_plotting(
        self,
        f_hndl,
        tt,
        states,
        show_sig,
        plt_inds,
        sig_bnd,
        color,
        marker,
        state_lbl,
        added_sig_lbl,
        added_state_lbl,
        scat=None,
    ):
        if scat is None:
            if not added_state_lbl:
                scat = f_hndl.axes[0].scatter(
                    [], [], color=color, edgecolors=(0, 0, 0), marker=marker
                )
            else:
                scat = f_hndl.axes[0].scatter(
                    [],
                    [],
                    color=color,
                    edgecolors=(0, 0, 0),
                    marker=marker,
                    label=state_lbl,
                )
        if len(states) == 0:
            return scat
        x = np.concatenate(states, axis=1)
        if show_sig:
            sigs = [None] * len(states)
            for ii, cov in enumerate(self._covs[tt]):
                sig = np.zeros((2, 2))
                sig[0, 0] = cov[plt_inds[0], plt_inds[0]]
                sig[0, 1] = cov[plt_inds[0], plt_inds[1]]
                sig[1, 0] = cov[plt_inds[1], plt_inds[0]]
                sig[1, 1] = cov[plt_inds[1], plt_inds[1]]
                sigs[ii] = sig
            # plot
            for ii, sig in enumerate(sigs):
                if sig is None:
                    continue
                w, h, a = pltUtil.calc_error_ellipse(sig, sig_bnd)
                if not added_sig_lbl:
                    s = r"${}\sigma$ Error Ellipses".format(sig_bnd)
                    e = Ellipse(
                        xy=x[plt_inds, ii],
                        width=w,
                        height=h,
                        angle=a,
                        zorder=-10000,
                        animated=True,
                        label=s,
                    )
                else:
                    e = Ellipse(
                        xy=x[plt_inds, ii],
                        width=w,
                        height=h,
                        angle=a,
                        zorder=-10000,
                        animated=True,
                    )
                e.set_clip_box(f_hndl.axes[0].bbox)
                e.set_alpha(0.15)
                e.set_facecolor(color)
                f_hndl.axes[0].add_patch(e)
        scat.set_offsets(x[plt_inds[0:2], :].T)
        return scat

    def plot_states(
        self,
        plt_inds,
        state_lbl="States",
        ttl=None,
        state_color=None,
        x_lbl=None,
        y_lbl=None,
        **kwargs,
    ):
        """Plots the best estimate for the states.

        This assumes that the states have been extracted. It's designed to plot
        two of the state variables (typically x/y position). The error ellipses
        are calculated according to :cite:`Hoover1984_AlgorithmsforConfidenceCirclesandEllipses`

        Keyword arguments are processed with
        :meth:`gncpy.plotting.init_plotting_opts`. This function
        implements

            - f_hndl
            - true_states
            - sig_bnd
            - rng
            - meas_inds
            - lgnd_loc
            - marker

        Parameters
        ----------
        plt_inds : list
            List of indices in the state vector to plot
        state_lbl : string
            Value to appear in legend for the states. Only appears if the
            legend is shown
        ttl : string, optional
            Title for the plot, if None a default title is generated. The default
            is None.
        x_lbl : string
            Label for the x-axis.
        y_lbl : string
            Label for the y-axis.

        Returns
        -------
        Matplotlib figure
            Instance of the matplotlib figure used
        """
        opts = pltUtil.init_plotting_opts(**kwargs)
        f_hndl = opts["f_hndl"]
        true_states = opts["true_states"]
        sig_bnd = opts["sig_bnd"]
        rng = opts["rng"]
        meas_inds = opts["meas_inds"]
        lgnd_loc = opts["lgnd_loc"]
        marker = opts["marker"]
        if ttl is None:
            ttl = "State Estimates"
        if rng is None:
            rng = rnd.default_rng(1)
        if x_lbl is None:
            x_lbl = "x-position"
        if y_lbl is None:
            y_lbl = "y-position"
        plt_meas = meas_inds is not None
        show_sig = sig_bnd is not None and self.save_covs

        s_lst = deepcopy(self._states)
        x_dim = None

        if f_hndl is None:
            f_hndl = plt.figure()
            f_hndl.add_subplot(1, 1, 1)
        # get state dimension
        for states in s_lst:
            if len(states) > 0:
                x_dim = states[0].size
                break
        # get array of all state values for each label
        added_sig_lbl = False
        added_true_lbl = False
        added_state_lbl = False
        added_meas_lbl = False
        r = rng.random()
        b = rng.random()
        g = rng.random()
        if state_color is None:
            color = (r, g, b)
        else:
            color = state_color
        for tt, states in enumerate(s_lst):
            if len(states) == 0:
                continue
            x = np.concatenate(states, axis=1)
            if show_sig:
                sigs = [None] * len(states)
                for ii, cov in enumerate(self._covs[tt]):
                    sig = np.zeros((2, 2))
                    sig[0, 0] = cov[plt_inds[0], plt_inds[0]]
                    sig[0, 1] = cov[plt_inds[0], plt_inds[1]]
                    sig[1, 0] = cov[plt_inds[1], plt_inds[0]]
                    sig[1, 1] = cov[plt_inds[1], plt_inds[1]]
                    sigs[ii] = sig
                # plot
                for ii, sig in enumerate(sigs):
                    if sig is None:
                        continue
                    w, h, a = pltUtil.calc_error_ellipse(sig, sig_bnd)
                    if not added_sig_lbl:
                        s = r"${}\sigma$ Error Ellipses".format(sig_bnd)
                        e = Ellipse(
                            xy=x[plt_inds, ii],
                            width=w,
                            height=h,
                            angle=a,
                            zorder=-10000,
                            label=s,
                        )
                        added_sig_lbl = True
                    else:
                        e = Ellipse(
                            xy=x[plt_inds, ii],
                            width=w,
                            height=h,
                            angle=a,
                            zorder=-10000,
                        )
                    e.set_clip_box(f_hndl.axes[0].bbox)
                    e.set_alpha(0.15)
                    e.set_facecolor(color)
                    f_hndl.axes[0].add_patch(e)
            if not added_state_lbl:
                f_hndl.axes[0].scatter(
                    x[plt_inds[0], :],
                    x[plt_inds[1], :],
                    color=color,
                    edgecolors=(0, 0, 0),
                    marker=marker,
                    label=state_lbl,
                )
                added_state_lbl = True
            else:
                f_hndl.axes[0].scatter(
                    x[plt_inds[0], :],
                    x[plt_inds[1], :],
                    color=color,
                    edgecolors=(0, 0, 0),
                    marker=marker,
                )
        # if true states are available then plot them
        if true_states is not None:
            if x_dim is None:
                for states in true_states:
                    if len(states) > 0:
                        x_dim = states[0].size
                        break
            max_true = max([len(x) for x in true_states])
            x = np.nan * np.ones((x_dim, len(true_states), max_true))
            for tt, states in enumerate(true_states):
                for ii, state in enumerate(states):
                    x[:, [tt], ii] = state.copy()
            for ii in range(0, max_true):
                if not added_true_lbl:
                    f_hndl.axes[0].plot(
                        x[plt_inds[0], :, ii],
                        x[plt_inds[1], :, ii],
                        color="k",
                        marker=".",
                        label="True Trajectories",
                    )
                    added_true_lbl = True
                else:
                    f_hndl.axes[0].plot(
                        x[plt_inds[0], :, ii],
                        x[plt_inds[1], :, ii],
                        color="k",
                        marker=".",
                    )
        if plt_meas:
            meas_x = []
            meas_y = []
            for meas_tt in self._meas_tab:
                mx_ii = [m[meas_inds[0]].item() for m in meas_tt]
                my_ii = [m[meas_inds[1]].item() for m in meas_tt]
                meas_x.extend(mx_ii)
                meas_y.extend(my_ii)
            color = (128 / 255, 128 / 255, 128 / 255)
            meas_x = np.asarray(meas_x)
            meas_y = np.asarray(meas_y)
            if not added_meas_lbl:
                f_hndl.axes[0].scatter(
                    meas_x,
                    meas_y,
                    zorder=-1,
                    alpha=0.35,
                    color=color,
                    marker="^",
                    edgecolors=(0, 0, 0),
                    label="Measurements",
                )
            else:
                f_hndl.axes[0].scatter(
                    meas_x,
                    meas_y,
                    zorder=-1,
                    alpha=0.35,
                    color=color,
                    marker="^",
                    edgecolors=(0, 0, 0),
                )
        f_hndl.axes[0].grid(True)
        pltUtil.set_title_label(f_hndl, 0, opts, ttl=ttl, x_lbl=x_lbl, y_lbl=y_lbl)

        if lgnd_loc is not None:
            plt.legend(loc=lgnd_loc)
        plt.tight_layout()

        return f_hndl

    def animate_state_plot(
        self,
        plt_inds,
        state_lbl="States",
        state_color=None,
        interval=250,
        repeat=True,
        repeat_delay=1000,
        save_path=None,
        **kwargs,
    ):
        """Creates an animated plot of the states.

        Parameters
        ----------
        plt_inds : list
            indices of the state vector to plot.
        state_lbl : string, optional
            label for the states. The default is 'States'.
        state_color : tuple, optional
            3-tuple for rgb value. The default is None.
        interval : int, optional
            interval of the animation in ms. The default is 250.
        repeat : bool, optional
            flag indicating if the animation loops. The default is True.
        repeat_delay : int, optional
            delay between loops in ms. The default is 1000.
        save_path : string, optional
            file path and name to save the gif, does not save if not given.
            The default is None.
        **kwargs : dict, optional
            Standard plotting options for
            :meth:`gncpy.plotting.init_plotting_opts`. This function
            implements

                - f_hndl
                - sig_bnd
                - rng
                - meas_inds
                - lgnd_loc
                - marker

        Returns
        -------
        anim :
            handle to the animation.

        """
        opts = pltUtil.init_plotting_opts(**kwargs)
        f_hndl = opts["f_hndl"]
        sig_bnd = opts["sig_bnd"]
        rng = opts["rng"]
        meas_inds = opts["meas_inds"]
        lgnd_loc = opts["lgnd_loc"]
        marker = opts["marker"]

        plt_meas = meas_inds is not None
        show_sig = sig_bnd is not None and self.save_covs

        f_hndl.axes[0].grid(True)
        pltUtil.set_title_label(
            f_hndl,
            0,
            opts,
            ttl="State Estimates",
            x_lbl="x-position",
            y_lbl="y-position",
        )

        fr_number = f_hndl.axes[0].annotate(
            "0",
            (0, 1),
            xycoords="axes fraction",
            xytext=(10, -10),
            textcoords="offset points",
            ha="left",
            va="top",
            animated=False,
        )

        added_sig_lbl = False
        added_state_lbl = False
        added_meas_lbl = False
        r = rng.random()
        b = rng.random()
        g = rng.random()
        if state_color is None:
            s_color = (r, g, b)
        else:
            s_color = state_color
        state_scat = f_hndl.axes[0].scatter(
            [], [], color=s_color, edgecolors=(0, 0, 0), marker=marker, label=state_lbl
        )
        meas_scat = None
        if plt_meas:
            m_color = (128 / 255, 128 / 255, 128 / 255)

            if meas_scat is None:
                if not added_meas_lbl:
                    lbl = "Measurements"
                    meas_scat = f_hndl.axes[0].scatter(
                        [],
                        [],
                        zorder=-1,
                        alpha=0.35,
                        color=m_color,
                        marker="^",
                        edgecolors="k",
                        label=lbl,
                    )
                    added_meas_lbl = True
                else:
                    meas_scat = f_hndl.axes[0].scatter(
                        [],
                        [],
                        zorder=-1,
                        alpha=0.35,
                        color=m_color,
                        marker="^",
                        edgecolors="k",
                    )

        def update(tt, *fargs):
            nonlocal added_sig_lbl
            nonlocal added_state_lbl
            nonlocal added_meas_lbl
            nonlocal state_scat
            nonlocal meas_scat
            nonlocal fr_number

            fr_number.set_text("Timestep: {j}".format(j=tt))

            states = self._states[tt]
            state_scat = self.__ani_state_plotting(
                f_hndl,
                tt,
                states,
                show_sig,
                plt_inds,
                sig_bnd,
                s_color,
                marker,
                state_lbl,
                added_sig_lbl,
                added_state_lbl,
                scat=state_scat,
            )
            added_sig_lbl = True
            added_state_lbl = True

            if plt_meas:
                meas_tt = self._meas_tab[tt]

                meas_x = [m[meas_inds[0]].item() for m in meas_tt]
                meas_y = [m[meas_inds[1]].item() for m in meas_tt]

                meas_x = np.asarray(meas_x)
                meas_y = np.asarray(meas_y)
                meas_scat.set_offsets(np.array([meas_x, meas_y]).T)

        # plt.figure(f_hndl.number)
        anim = animation.FuncAnimation(
            f_hndl,
            update,
            frames=len(self._states),
            interval=interval,
            repeat_delay=repeat_delay,
            repeat=repeat,
        )

        if lgnd_loc is not None:
            plt.legend(loc=lgnd_loc)
        if save_path is not None:
            writer = animation.PillowWriter(fps=30)
            anim.save(save_path, writer=writer)
        return anim
    





class GGIW_GLMB(RandomFiniteSetBase):
    """
    Delta-Generalized Labeled Multi-Bernoulli filter for Gamma Gaussian Inverse Wishart distributions for extended target tracking. 

    Restructured to account for GGIW stuff while also sticking with the ETT SERUMS classes that we've wrote. 

    Note: birth_terms is a list of tuples including the GGIW component and the Probability of birth.  
    """

    class _TabEntry:
        
        def __init__(self):
            self.label = ()  # time step born, index of birth model born from
            self.distrib_weights_hist = []  # list of weights of the probDensity
            self.meas_assoc_hist = (
                []
            )  # list indices into measurement list per time step

            self.GGIW_hist = []   # list of lists of GGIW objects for each timestep
            
            self.time_index = None

        def __str__(self):
            s  = f"Label: {self.label}\n"
            s += f"Time Index: {self.time_index}\n"
            s += f"Measurement Association History: {self.meas_assoc_hist}\n"
            s += f"Weight History: {self.distrib_weights_hist}\n"
            s += "State History:\n"
            cols = [hist[0].mean for hist in self.GGIW_hist]
            M = np.hstack(cols)
            s += np.array2string(M,
                                precision=3,
                                suppress_small=True, 
                                max_line_width=420)
            return s

        def setup(self,tab):
            """Use to avoid expensive deepcopy."""
            self.label = tab.label
            self.distrib_weights_hist = tab.distrib_weights_hist.copy()
            self.meas_assoc_hist = tab.meas_assoc_hist.copy()
            
            self.GGIW_hist = [g for g in tab.GGIW_hist]

            self.time_index = tab.time_index

    class _HypothesisHelper:
        def __init__(self):
            self.assoc_prob = 0
            self.track_set = []   # indices in lookup table

        def __str__(self):
            s = ""
            s += f"Association Probability: {self.assoc_prob} \n"
            s += f"Track Set: {self.track_set} \n"
            s += f"Number of Tracks: {len(self.track_set)} \n"
            return s

        @property
        def num_tracks(self):
            return len(self.track_set)

    class _ExtractHistHelper:
        def __init__(self):
            self.label = ()
            self.meas_ind_hist = []
            self.b_time_index = None
            self.GGIWs = [] 

        def __str__(self):
            return f"Extract History Helper Object for label: {self.label}"

    def __init__(
        self,
        clustering_obj,
        req_births=None,
        req_surv=None,
        req_upd=None,
        gating_on=False,
        prune_threshold=10**-15,
        max_hyps=3000,
        decimal_places=2,
        save_measurements=False,
        partition_thresh = 1, 
        **kwargs,
    ):
        self.req_births = req_births
        self.req_surv = req_surv
        self.req_upd = req_upd
        self.gating_on = gating_on
        self.prune_threshold = prune_threshold
        self.max_hyps = max_hyps
        self.decimal_places = decimal_places
        self.save_measurements = save_measurements
        self.partition_thresh = partition_thresh 

        if clustering_obj is None:
            raise("Please choose a clustering_obj. ")
        else:
            self._clustering_obj = clustering_obj
    
        self._track_tab = []  # list of all possible tracks
        self._labels = []  # local copy for internal modification
        self._extractable_hists = []

        self._filter = None
        self._baseFilter = None

        hyp0 = self._HypothesisHelper()
        hyp0.assoc_prob = 0.1
        hyp0.track_set = []
        self._hypotheses = [hyp0]  # list of _HypothesisHelper objects

        self._card_dist = []  # probability of having index # as cardinality

        """ linear index corresponding to timestep, manually updated. Used
            to index things since timestep in label can have decimals. Must
            be updated once per time step."""
        self._time_index_cntr = 0

        self.ospa2 = None
        self.ospa2_localization = None
        self.ospa2_cardinality = None
        self._ospa2_params = {}

        super().__init__(**kwargs)
        self._GGIW_objs = [[]]

    def save_filter_state(self):
        """Saves filter variables so they can be restored later.

        Note that to pickle the resulting dictionary the :code:`dill` package
        may need to be used due to potential pickling of functions.
        """
        filt_state = super().save_filter_state()

        filt_state["req_births"] = self.req_births
        filt_state["req_surv"] = self.req_surv
        filt_state["req_upd"] = self.req_upd
        filt_state["gating_on"] = self.gating_on
        filt_state["prune_threshold"] = self.prune_threshold
        filt_state["max_hyps"] = self.max_hyps
        filt_state["decimal_places"] = self.decimal_places
        filt_state["save_measurements"] = self.save_measurements

        filt_state["_track_tab"] = self._track_tab
        filt_state["_labels"] = self._labels
        filt_state["_extractable_hists"] = self._extractable_hists

        if self._baseFilter is not None:
            filt_state["_baseFilter"] = (
                type(self._baseFilter),
                self._baseFilter.save_filter_state(),
            )
        else:
            filt_state["_baseFilter"] = (None, self._baseFilter)
        filt_state["_hypotheses"] = self._hypotheses
        filt_state["_card_dist"] = self._card_dist
        filt_state["_time_index_cntr"] = self._time_index_cntr

        filt_state["ospa2"] = self.ospa2
        filt_state["ospa2_localization"] = self.ospa2_localization
        filt_state["ospa2_cardinality"] = self.ospa2_cardinality
        filt_state["_ospa2_params"] = self._ospa_params

        return filt_state

    def load_filter_state(self, filt_state):
        """Initializes filter using saved filter state.

        Attributes
        ----------
        filt_state : dict
            Dictionary generated by :meth:`save_filter_state`.
        """
        super().load_filter_state(filt_state)

        self.req_births = filt_state["req_births"]
        self.req_surv = filt_state["req_surv"]
        self.req_upd = filt_state["req_upd"]
        self.gating_on = filt_state["gating_on"]
        self.prune_threshold = filt_state["prune_threshold"]
        self.max_hyps = filt_state["max_hyps"]
        self.decimal_places = filt_state["decimal_places"]
        self.save_measurements = filt_state["save_measurements"]

        self._track_tab = filt_state["_track_tab"]
        self._labels = filt_state["_labels"]
        self._extractable_hists = filt_state["_extractable_hists"]

        cls_type = filt_state["_baseFilter"][0]
        if cls_type is not None:
            self._baseFilter = cls_type()
            self._baseFilter.load_filter_state(filt_state["_baseFilter"][1])
        else:
            self._baseFilter = None
        self._hypotheses = filt_state["_hypotheses"]
        self._card_dist = filt_state["_card_dist"]
        self._time_index_cntr = filt_state["_time_index_cntr"]

        self.ospa2 = filt_state["ospa2"]
        self.ospa2_localization = filt_state["ospa2_localization"]
        self.ospa2_cardinality = filt_state["ospa2_cardinality"]
        self._ospa2_params = filt_state["_ospa2_params"]


    @property
    def GGIWs(self):
        """Read only list of extracted GGIW Components. """
        return self._GGIW_objs
    
    @property
    def labels(self):
        """Read only list of extracted labels.

        This is a list with 1 element per timestep, and each element is a list
        of the best labels extracted at that timestep. The order of each
        element corresponds to the state order.
        """
        return self._labels
    
    @property
    def filter(self):
        """Inner filter handling dynamics, must be a gncpy.filters.BayesFilter."""
        return self._filter

    @filter.setter
    def filter(self, val):
        self._baseFilter = deepcopy(val)
        self._filter = val

    @property
    def cardinality(self):
        """Cardinality estimate."""
        return np.argmax(self._card_dist)
    
    def _gen_birth_tab(self, timestep):
        log_cost = []
        birth_tab = []
        for ii, (distrib,p) in enumerate(self.birth_terms):
            cost = p / (1 - p)
            log_cost.append(-np.log(cost))
            entry = self._TabEntry()
            entry.GGIW_hist = [None]
            entry.distrib_weights_hist = [None] 

            entry.distrib_weights_hist[0] = distrib.weights.copy()
            entry.GGIW_hist[0] = [distrib[0]]

            entry.label = (round(timestep, self.decimal_places), ii)
            entry.time_index = self._time_index_cntr
            birth_tab.append(entry)
        return birth_tab, log_cost

    def _gen_birth_hyps(self, paths, hyp_costs):
        birth_hyps = []
        tot_b_prob = sum([np.log(1 - x[1]) for x in self.birth_terms])
        for p, c in zip(paths, hyp_costs):
            hyp = self._HypothesisHelper()
            # NOTE: this may suffer from underflow and can be improved
            hyp.assoc_prob = tot_b_prob - c.item()
            hyp.track_set = p
            birth_hyps.append(hyp)
        lse = log_sum_exp([x.assoc_prob for x in birth_hyps])
        for ii in range(0, len(birth_hyps)):
            birth_hyps[ii].assoc_prob = np.exp(birth_hyps[ii].assoc_prob - lse)
        return birth_hyps

    def _predict_track_tab_entry(self, tab, timestep, filt_args):
        """Updates table entries probability density."""
        newTab = self._TabEntry()
        newTab.setup(tab) 
        new_GGIW_hist = [None] * len(newTab.GGIW_hist[-1])  

        for ii, dist in enumerate(newTab.GGIW_hist[-1]): 
            new_GGIW_hist[ii] = self.filter.predict(timestep, dist, filt_args)
        newTab.GGIW_hist.append(new_GGIW_hist) 
        newTab.distrib_weights_hist.append(newTab.distrib_weights_hist[-1].copy())
        return newTab
    
    def _gen_surv_tab(self, timestep, filt_args):
        surv_tab = []
        for ii, track in enumerate(self._track_tab):
            entry = self._predict_track_tab_entry(track, timestep, filt_args)

            surv_tab.append(entry)
        return surv_tab

    def _gen_surv_hyps(self, avg_prob_survive, avg_prob_death):
        surv_hyps = []
        sum_sqrt_w = 0
        # avg_prob_mm =
        for hyp in self._hypotheses:
            sum_sqrt_w = sum_sqrt_w + np.sqrt(hyp.assoc_prob)
        for hyp in self._hypotheses:
            if hyp.num_tracks == 0:
                new_hyp = self._HypothesisHelper()
                new_hyp.assoc_prob = np.log(hyp.assoc_prob)
                new_hyp.track_set = hyp.track_set
                surv_hyps.append(new_hyp)
            else:
                cost = avg_prob_survive[hyp.track_set] / avg_prob_death[hyp.track_set]
                log_cost = -np.log(cost)  # this is length hyp.num_tracks
                k = np.round(self.req_surv * np.sqrt(hyp.assoc_prob) / sum_sqrt_w)
                (paths, hyp_cost) = k_shortest(np.array(log_cost), k)

                pdeath_log = np.sum(
                    [np.log(avg_prob_death[ii]) for ii in hyp.track_set]
                )

                for p, c in zip(paths, hyp_cost):
                    new_hyp = self._HypothesisHelper()
                    new_hyp.assoc_prob = pdeath_log + np.log(hyp.assoc_prob) - c.item()
                    if len(p) > 0:
                        new_hyp.track_set = [hyp.track_set[ii] for ii in p]
                    else:
                        new_hyp.track_set = []
                    surv_hyps.append(new_hyp)
        lse = log_sum_exp([x.assoc_prob for x in surv_hyps])
        for ii in range(0, len(surv_hyps)):
            surv_hyps[ii].assoc_prob = np.exp(surv_hyps[ii].assoc_prob - lse)
        return surv_hyps
    
    def _calc_avg_prob_surv_death(self):
        avg_prob_survive = self.prob_survive * np.ones(len(self._track_tab))
        avg_prob_death = 1 - avg_prob_survive

        return avg_prob_survive, avg_prob_death
    
    def _set_pred_hyps(self, birth_tab, birth_hyps, surv_hyps):
        self._hypotheses = []
        tot_w = 0
        for b_hyp in birth_hyps:
            for s_hyp in surv_hyps:
                new_hyp = self._HypothesisHelper()
                new_hyp.assoc_prob = b_hyp.assoc_prob * s_hyp.assoc_prob
                tot_w = tot_w + new_hyp.assoc_prob
                surv_lst = []
                for x in s_hyp.track_set:
                    surv_lst.append(x + len(birth_tab))
                new_hyp.track_set = b_hyp.track_set + surv_lst
                self._hypotheses.append(new_hyp)
        for ii in range(0, len(self._hypotheses)):
            n_val = self._hypotheses[ii].assoc_prob / tot_w
            self._hypotheses[ii].assoc_prob = n_val

    def _calc_card_dist(self, hyp_lst):
        """Calucaltes the cardinality distribution."""
        if len(hyp_lst) == 0:
            return [
                1,
            ]
        # card_dist = []
        # for ii in range(0, max(map(lambda x: x.num_tracks, hyp_lst)) + 1): 
        #     card = 0
        #     for hyp in hyp_lst:
        #         if hyp.num_tracks == ii:
        #             card = card + hyp.assoc_prob
        #     card_dist.append(card)
        # return card_dist

        max_card = max([x.num_tracks for x in hyp_lst]) if hyp_lst else 0
        card_dist = [0.0] * (max_card + 1)
        
        for hyp in hyp_lst:
            card = hyp.num_tracks
            card_dist[card] += hyp.assoc_prob
        
        # Ensure normalization
        total = sum(card_dist)
        if total > 0:
            card_dist = [p/total for p in card_dist]
        else:
            card_dist = [0.0] * len(card_dist)
            card_dist[0] = 1.0
            
        return card_dist
    
    def _clean_predictions(self):
        hash_lst = []
        for hyp in self._hypotheses:
            if len(hyp.track_set) == 0:
                lst = []
            else:
                sorted_inds = hyp.track_set.copy()
                sorted_inds.sort()
                lst = [int(x) for x in sorted_inds]
            h = hash("*".join(map(str, lst)))
            hash_lst.append(h)
        new_hyps = []
        used_hash = []
        for ii, h in enumerate(hash_lst):
            if h not in used_hash:
                used_hash.append(h)
                new_hyps.append(self._hypotheses[ii])
            else:
                new_ii = used_hash.index(h)
                new_hyps[new_ii].assoc_prob += self._hypotheses[ii].assoc_prob
        self._hypotheses = new_hyps

    def predict(self, timestep, filt_args={}):
        """Prediction step of the GLMB filter.

        This predicts new hypothesis, and propogates them to the next time
        step. It also updates the cardinality distribution.

        Parameters
        ----------
        timestep: float
            Current timestep.
        filt_args : dict, optional
            Passed to the inner filter. The default is {}.

        Returns
        -------
        None.
        """
        # Find cost for each birth track, and setup lookup table
        birth_tab, log_cost = self._gen_birth_tab(timestep)

        # get K best hypothesis, and their index in the lookup table
        (paths, hyp_costs) = k_shortest(np.array(log_cost), self.req_births)

        # calculate association probabilities for birth hypothesis
        birth_hyps = self._gen_birth_hyps(paths, hyp_costs)

        # Init and propagate surviving track table
        surv_tab = self._gen_surv_tab(timestep, filt_args)

        # Calculation for average survival/death probabilities
        (avg_prob_survive, avg_prob_death) = self._calc_avg_prob_surv_death()

        # loop over postierior components
        surv_hyps = self._gen_surv_hyps(avg_prob_survive, avg_prob_death)

        # self._card_dist = self._calc_card_dist(surv_hyps)

        # Get  predicted hypothesis by convolution
        self._track_tab = birth_tab + surv_tab
        self._set_pred_hyps(birth_tab, birth_hyps, surv_hyps)

        self._clean_predictions()

        self._card_dist = self._calc_card_dist(surv_hyps)


    def _inner_correct(
        self, timestep, meas, distrib_weight, GGIW_obj, filt_args
    ):
        # num_meas = len(meas) 
        
        # meas_d = meas[0].shape[0]

        # meas_arr = np.array(meas).reshape(num_meas, meas_d)
        
        new_GGIW, likely = self.filter.correct(timestep, meas, GGIW_obj, **filt_args) 

        new_w = distrib_weight * np.exp(likely)   # The GGIW EKF returns the log likelihood.  

        return new_GGIW, new_w

    def _correct_track_tab_entry(self, meas, tab, timestep, filt_args):
        newTab = self._TabEntry()
        newTab.setup(tab)
        
        depleted = False   # idk why this is here, later issue. 
        
        new_GGIW = [None] * len(newTab.distrib_weights_hist[-1])
        new_w = [None] * len(newTab.distrib_weights_hist[-1])

        for ii, (dist,w) in enumerate(zip(newTab.GGIW_hist[-1], newTab.distrib_weights_hist[-1])):
            new_GGIW[ii], new_w[ii] = self._inner_correct(timestep,meas,w,dist,filt_args)

        newTab.GGIW_hist[-1] = new_GGIW

        new_w = [w + np.finfo(float).eps for w in new_w]  

        if not depleted:
            cost = np.sum(new_w).item()
            newTab.distrib_weights_hist[-1] = [w / cost for w in new_w] 
        else:
            cost = 0
        return newTab, cost

    def _gen_cor_tab(self, num_meas, meas, timestep, filt_args):
        num_pred = len(self._track_tab)
        up_tab = [None] * (num_meas + 1) * num_pred 

        for ii, track in enumerate(self._track_tab): 
            entry = self._TabEntry()
            entry.setup(track)
            entry.meas_assoc_hist.append(None)
            up_tab[ii] = entry
        # measurement updated tracks

        all_cost_m = np.zeros((num_pred, num_meas))
        for emm, z in enumerate(meas):
            for ii, ent in enumerate(self._track_tab):

                meas_per_clust = len(z)
                meas_d = z[0].shape[0]
                z_array = np.array(z).reshape((meas_per_clust, meas_d)).transpose()

                s_to_ii = num_pred * emm + ii + num_pred
                (up_tab[s_to_ii], cost) = self._correct_track_tab_entry(
                    z_array, ent, timestep, filt_args
                )
                
                # update association history with current measurement index
                if up_tab[s_to_ii] is not None:
                    up_tab[s_to_ii].meas_assoc_hist.append(emm)
                all_cost_m[ii, emm] = cost
        return up_tab, all_cost_m

    def _gen_cor_hyps(
        self, num_meas, avg_prob_detect, avg_prob_miss_detect, all_cost_m
    ):
        num_pred = len(self._track_tab)
        up_hyps = []
        if num_meas == 0:
            for hyp in self._hypotheses:
                pmd_log = np.sum(
                    [np.log(avg_prob_miss_detect[ii]) for ii in hyp.track_set]
                )
                hyp.assoc_prob = -self.clutter_rate + pmd_log + np.log(hyp.assoc_prob)
                up_hyps.append(hyp)
        else:
            clutter = self.clutter_rate * self.clutter_den
            ss_w = 0
            for p_hyp in self._hypotheses:
                ss_w += np.sqrt(p_hyp.assoc_prob)
            for p_hyp in self._hypotheses:
                if p_hyp.num_tracks == 0:  # all clutter
                    new_hyp = self._HypothesisHelper()
                    new_hyp.assoc_prob = (
                        -self.clutter_rate
                        + num_meas * np.log(clutter)
                        + np.log(p_hyp.assoc_prob)
                    )
                    new_hyp.track_set = p_hyp.track_set.copy()
                    up_hyps.append(new_hyp)
                else:
                    pd = np.array([avg_prob_detect[ii] for ii in p_hyp.track_set])
                    pmd = np.array([avg_prob_miss_detect[ii] for ii in p_hyp.track_set])
                    ratio = pd / pmd

                    ratio = ratio.reshape((ratio.size, 1))
                    ratio = np.tile(ratio, (1, num_meas))

                    cost_m = np.zeros(all_cost_m[p_hyp.track_set, :].shape)
                    for ii, ts in enumerate(p_hyp.track_set):
                        cost_m[ii, :] = ratio[ii] * all_cost_m[ts, :] / clutter
                    max_row_inds, max_col_inds = np.where(cost_m >= np.inf)
                    if max_row_inds.size > 0:
                        cost_m[max_row_inds, max_col_inds] = np.finfo(float).max
                    min_row_inds, min_col_inds = np.where(cost_m <= 0.0)
                    if min_row_inds.size > 0:
                        cost_m[min_row_inds, min_col_inds] = np.finfo(float).eps  # 1
                    neg_log = -np.log(cost_m)
                    # if max_row_inds.size > 0:
                    #     neg_log[max_row_inds, max_col_inds] = -np.inf
                    # if min_row_inds.size > 0:
                    #     neg_log[min_row_inds, min_col_inds] = np.inf

                    m = np.round(self.req_upd * np.sqrt(p_hyp.assoc_prob) / ss_w)
                    m = int(m.item())
                    [assigns, costs] = murty_m_best(neg_log, m)

                    pmd_log = np.sum(
                        [np.log(avg_prob_miss_detect[ii]) for ii in p_hyp.track_set]
                    )
                    for a, c in zip(assigns, costs):
                        new_hyp = self._HypothesisHelper()
                        new_hyp.assoc_prob = (
                            -self.clutter_rate
                            + num_meas * np.log(clutter)
                            + pmd_log
                            + np.log(p_hyp.assoc_prob)
                            - c
                        )
                        new_hyp.track_set = list(
                            np.array(p_hyp.track_set) + num_pred * a
                        )
                        up_hyps.append(new_hyp)
        lse = log_sum_exp([x.assoc_prob for x in up_hyps])
        for ii in range(0, len(up_hyps)):
            up_hyps[ii].assoc_prob = np.exp(up_hyps[ii].assoc_prob - lse)
        return up_hyps

    def _calc_avg_prob_det_mdet(self):
        avg_prob_detect = self.prob_detection * np.ones(len(self._track_tab))
        avg_prob_miss_detect = 1 - avg_prob_detect

        return avg_prob_detect, avg_prob_miss_detect

    def _clean_updates(self):
        # print("Before update:")
        # print(f"Hypothesis 0: track_set = {self._hypotheses[0].track_set} \n ")

        used = [0] * len(self._track_tab)
        for hyp in self._hypotheses:
            for ii in hyp.track_set:
                if self._track_tab[ii] is not None:
                    used[ii] += 1
        nnz_inds = [idx for idx, val in enumerate(used) if val != 0]
        track_cnt = len(nnz_inds)

        new_inds = [None] * len(self._track_tab)
        for ii, v in zip(nnz_inds, [ii for ii in range(0, track_cnt)]):
            new_inds[ii] = v
        new_tab = [self._track_tab[ii] for ii in nnz_inds]
        new_hyps = []
        for ii, hyp in enumerate(self._hypotheses):
            if len(hyp.track_set) > 0:
                track_set = [new_inds[ii] for ii in hyp.track_set]
                if None in track_set:
                    continue
                hyp.track_set = track_set
            new_hyps.append(hyp)
        self._track_tab = new_tab
        self._hypotheses = new_hyps

        # print("After update:")
        # print(f"Hypothesis 0: track_set = {self._hypotheses[0].track_set} \n ")
        

    def correct(self, timestep, meas_in, filt_args={}):
        """Correction step of the GLMB filter.

        Notes
        -----
        This corrects the hypotheses based on the measurements and gates the
        measurements according to the class settings. It also updates the
        cardinality distribution.

        Parameters
        ----------
        timestep: float
            Current timestep.
        meas_in : list
            List of Nm x 1 numpy arrays each representing a measuremnt.
        filt_args : dict, optional
            keyword arguments to pass to the inner filters correct function.
            The default is {}.

        .. todo::
            Fix the measurement gating

        Returns
        -------
        None
        """
        # gate measurements by tracks
        if self.gating_on:
            warnings.warn("Gating not implemented yet. SKIPPING", RuntimeWarning)
            # means = []
            # covs = []
            # for ent in self._track_tab:
            #     means.extend(ent.probDensity.means)
            #     covs.extend(ent.probDensity.covariances)
            # meas = self._gate_meas(meas, means, covs)

        meas = self._clustering_obj.cluster(meas_in) 
        
        if self.save_measurements:
            self._meas_tab.append(deepcopy(meas))
        num_meas = len(meas)

        # missed detection tracks
        cor_tab, all_cost_m = self._gen_cor_tab(num_meas, meas, timestep, filt_args)

        # Calculation for average detection/missed probabilities
        avg_prob_det, avg_prob_mdet = self._calc_avg_prob_det_mdet()

        # component updates
        cor_hyps = self._gen_cor_hyps(num_meas, avg_prob_det, avg_prob_mdet, all_cost_m)

        # save values and cleanup
        self._track_tab = cor_tab
        self._hypotheses = cor_hyps
        self._card_dist = self._calc_card_dist(self._hypotheses)
        self._clean_updates()

    def _prune(self):
        """Removes hypotheses below a threshold.

        This should be called once per time step after the correction and
        before the state extraction.
        """
        # Find hypotheses with low association probabilities
        temp_assoc_probs = np.array([])
        for ii in range(0, len(self._hypotheses)):
            temp_assoc_probs = np.append(
                temp_assoc_probs, self._hypotheses[ii].assoc_prob
            )
        keep_indices = np.argwhere(temp_assoc_probs > self.prune_threshold).T
        keep_indices = keep_indices.flatten()

        # For re-weighing association probabilities
        new_sum = np.sum(temp_assoc_probs[keep_indices])
        self._hypotheses = [self._hypotheses[ii] for ii in keep_indices]
        for ii in range(0, len(keep_indices)):
            self._hypotheses[ii].assoc_prob = self._hypotheses[ii].assoc_prob / new_sum
        # Re-calculate cardinality
        self._card_dist = self._calc_card_dist(self._hypotheses)

    def _cap(self):
        """Removes least likely hypotheses until a maximum number is reached.

        This should be called once per time step after pruning and
        before the state extraction.
        """
        # Determine if there are too many hypotheses
        if len(self._hypotheses) > self.max_hyps:
            temp_assoc_probs = np.array([])
            for ii in range(0, len(self._hypotheses)):
                temp_assoc_probs = np.append(
                    temp_assoc_probs, self._hypotheses[ii].assoc_prob
                )
            sorted_indices = np.argsort(temp_assoc_probs)

            # Reverse order to get descending array
            sorted_indices = sorted_indices[::-1]

            # Take the top n assoc_probs, where n = max_hyps
            keep_indices = np.array([], dtype=np.int64)
            for ii in range(0, self.max_hyps):
                keep_indices = np.append(keep_indices, int(sorted_indices[ii]))
            # Assign to class
            self._hypotheses = [self._hypotheses[ii] for ii in keep_indices]

            # Normalize association probabilities
            new_sum = 0
            for ii in range(0, len(self._hypotheses)):
                new_sum = new_sum + self._hypotheses[ii].assoc_prob
            for ii in range(0, len(self._hypotheses)):
                self._hypotheses[ii].assoc_prob = (
                    self._hypotheses[ii].assoc_prob / new_sum
                )
            # Re-calculate cardinality
            self._card_dist = self._calc_card_dist(self._hypotheses)

    def _extract_helper(self, track):
        GGIWs = [None] * len(track.GGIW_hist) 
        for ii, (w_lst, GGIW_lst) in enumerate(
            zip(track.distrib_weights_hist, track.GGIW_hist)
        ):
            idx = np.argmax(w_lst)
            GGIWs[ii] = GGIW_lst[idx] 
            
        return GGIWs

    def _update_extract_hist(self, idx_cmp):
        used_meas_inds = [[] for ii in range(self._time_index_cntr)]
        used_labels = []
        new_extract_hists = [None] * len(self._hypotheses[idx_cmp].track_set) 
        for ii, track in enumerate(
            [
                self._track_tab[trk_ind]
                for trk_ind in self._hypotheses[idx_cmp].track_set
            ]
        ): 
            new_extract_hists[ii] = self._ExtractHistHelper()
            new_extract_hists[ii].label = track.label
            new_extract_hists[ii].meas_ind_hist = track.meas_assoc_hist.copy()
            new_extract_hists[ii].b_time_index = track.time_index
            (
                new_extract_hists[ii].GGIWs
            ) = self._extract_helper(track)

            used_labels.append(track.label)

            for t_inds_after_b, meas_ind in enumerate(
                new_extract_hists[ii].meas_ind_hist
            ):
                tt = new_extract_hists[ii].b_time_index + t_inds_after_b
                if meas_ind is not None and meas_ind not in used_meas_inds[tt]:
                    used_meas_inds[tt].append(meas_ind)
        good_inds = []
        for ii, existing in enumerate(self._extractable_hists):
            used = existing.label in used_labels
            if used:
                continue
            for t_inds_after_b, meas_ind in enumerate(existing.meas_ind_hist):
                tt = existing.b_time_index + t_inds_after_b
                used = meas_ind is not None and meas_ind in used_meas_inds[tt]
                if used:
                    break
            if not used:
                good_inds.append(ii)
        self._extractable_hists = [self._extractable_hists[ii] for ii in good_inds]
        self._extractable_hists.extend(new_extract_hists)

    def extract_states(self, update=True, calc_states=True):
        """Extracts the best state estimates.

        This extracts the best states from the distribution. It should be
        called once per time step after the correction function. This calls
        both the inner filters predict and correct functions so the keyword
        arguments must contain any additional variables needed by those
        functions.

        Parameters
        ----------
        update : bool, optional
            Flag indicating if the label history should be updated. This should
            be done once per timestep and can be disabled if calculating states
            after the final timestep. The default is True.
        calc_states : bool, optional
            Flag indicating if the states should be calculated based on the
            label history. This only needs to be done before the states are used.
            It can simply be called once after the end of the simulation. The
            default is true.

        Returns
        -------
        idx_cmp : int
            Index of the hypothesis table used when extracting states.
        """
        card = np.argmax(self._card_dist)
        tracks_per_hyp = np.array([x.num_tracks for x in self._hypotheses])
        weight_per_hyp = np.array([x.assoc_prob for x in self._hypotheses]) 

        self._GGIW_objs = [[] for ii in range(self._time_index_cntr)]
        self._labels = [[] for ii in range(self._time_index_cntr)]  

        if len(tracks_per_hyp) == 0:
            return None
        # idx_cmp = np.argmax(weight_per_hyp * (tracks_per_hyp == card)) 

        max_weight = np.max(weight_per_hyp * (tracks_per_hyp == card))
        idx_cmp_candidates = np.where(weight_per_hyp * (tracks_per_hyp == card) == max_weight)[0]  
        
        idx_cmp = idx_cmp_candidates[0]

        # idx_cmp = sorted(idx_cmp_candidates,
        #          key=lambda i: tuple(sorted(self._hypotheses[i].track_set)))[0]

        # print(weight_per_hyp * (tracks_per_hyp == card))

        if update:
            self._update_extract_hist(idx_cmp) 

        if calc_states:
            for existing in self._extractable_hists:
                for t_inds_after_b, g in enumerate(existing.GGIWs):
                    tt = existing.b_time_index + t_inds_after_b
                    # if len(self._labels[tt]) == 0:
                    #     self._states[tt] = [s]
                    #     self._labels[tt] = [existing.label]
                    #     self._covs[tt] = [c]
                    # else:
                    self._GGIW_objs[tt].append(g)
                    self._labels[tt].append(existing.label) 
        if not update and not calc_states:
            warnings.warn("Extracting states performed no actions")
            
        return idx_cmp 
    
    def cleanup(
        self,
        enable_prune=True,
        enable_cap=True,
        enable_extract=True,
        extract_kwargs=None,
    ):
        """Performs the cleanup step of the filter.

        This can prune, cap, and extract states. It must be called once per
        timestep, even if all three functions are disabled. This is to ensure
        that internal counters for tracking linear timestep indices are properly
        incremented. If this is called with `enable_extract` set to true then
        the extract states method does not need to be called separately. It is
        recommended to call this function instead of
        :meth:`carbs.swarm_estimator.tracker.GeneralizedLabeledMultiBernoulli.extract_states`
        directly.

        Parameters
        ----------
        enable_prune : bool, optional
            Flag indicating if prunning should be performed. The default is True.
        enable_cap : bool, optional
            Flag indicating if capping should be performed. The default is True.
        enable_extract : bool, optional
            Flag indicating if state extraction should be performed. The default is True.
        extract_kwargs : dict, optional
            Additional arguments to pass to :meth:`.extract_states`. The
            default is None. Only used if extracting states.

        Returns
        -------
        None.

        """
        self._time_index_cntr += 1

        if enable_prune:
            self._prune()
        if enable_cap:
            self._cap()
        if enable_extract:
            if extract_kwargs is None:
                extract_kwargs = {}
            self.extract_states(**extract_kwargs)

    def plot_states_labels(
        self,
        plt_inds=[0, 1],
        ttl="Labeled State Trajectories with Extents",
        ax=None,
        **kwargs,
        ):
        """
        Plot per‑label trajectories (as lines) **and** the latest confidence
        ellipses produced by each GGIW object.

        Parameters
        ----------
        plt_inds : tuple(int, int)
            State indices to plot, e.g. (0,1) → x/y.
        ttl : str
            Figure title.
        ax : matplotlib.axes.Axes, optional
            Axes to plot on; new axes created if None.
        """
        import numpy as np
        import matplotlib.pyplot as plt

        if ax is None:
            fig, ax = plt.subplots()
        else:
            fig = ax.figure

        # --- gather trajectory history for every label --------------------------
        traj = {}          # label → list of means over time
        latest = {}        # label → latest GGIW object (for ellipse)

        for g_list, lbl_list in zip(self._GGIW_objs, self._labels):
            for ggiw, lbl in zip(g_list, lbl_list):
                traj.setdefault(lbl, []).append(ggiw.mean[plt_inds].flatten())
                latest[lbl] = ggiw   # overwrites until last time‑step

        # --- unique colors per label -------------------------------------------
        cmap = plt.get_cmap("tab20")
        colors = {lbl: cmap(i % 20) for i, lbl in enumerate(traj)}

        # --- plot everything ----------------------------------------------------
        for lbl, pts in traj.items():
            pts = np.stack(pts, axis=1)
            col = colors[lbl]

            # trajectory line + final point
            ax.plot(pts[0], pts[1], "-", color=col, linewidth=1.5)
            ax.scatter(pts[0, -1], pts[1, -1], color=col, edgecolor="k", zorder=5,
                    label=f"Label {lbl}")

            # confidence ellipse from SERUMS helper (h ≈ 0.95 by default)
            latest[lbl].plot_confidence_extents(
                h=0.95, plt_inds=list(plt_inds), ax=ax, color=col
            )

        # cosmetics
        ax.set_title(ttl)
        ax.set_xlabel(f"state[{plt_inds[0]}]")
        ax.set_ylabel(f"state[{plt_inds[1]}]")
        ax.set_aspect("equal", "box")
        ax.grid(True, linewidth=0.3) 

        return fig



class GGIW_JGLMB(GGIW_GLMB):
    """Implements a Joint Generalized Labeled Multi-Bernoulli Filter.

    The Joint GLMB is designed to call predict and correct simultaneously,
    as a single joint prediction-correction step.
    Calling them asynchronously may cause poor performance.

    Notes
    -----
    This is based on :cite:`Vo2017_AnEfficientImplementationoftheGeneralizedLabeledMultiBernoulliFilter`.
    It does not account for agents spawned from existing tracks, only agents
    birthed from the given birth model.
    """

    def __init__(self, rng=None, **kwargs):
        super().__init__(**kwargs)
        self._old_track_tab_len = len(self._track_tab)
        self._update_has_been_called = (
            True  # used to denote if the update function should be called or not.
        )
        if rng is None:
            self._rng = np.random.default_rng()
        else:
            self._rng = rng

    def save_filter_state(self):
        """Saves filter variables so they can be restored later.

        Note that to pickle the resulting dictionary the :code:`dill` package
        may need to be used due to potential pickling of functions.
        """
        filt_state = super().save_filter_state()

        filt_state["_old_track_tab_len"] = self._old_track_tab_len

        return filt_state

    def load_filter_state(self, filt_state):
        """Initializes filter using saved filter state.

        Attributes
        ----------
        filt_state : dict
            Dictionary generated by :meth:`save_filter_state`.
        """
        super().load_filter_state(filt_state)

        self._old_track_tab_len = filt_state["_old_track_tab_len"]

    def predict(self, timestep, filt_args={}):
        """Prediction step of the JGLMB filter.

        This predicts new hypothesis, and propogates them to the next time
        step. Because this calls
        the inner filter's predict function, the keyword arguments must contain
        any information needed by that function.

        Parameters
        ----------
        timestep: float
            Current timestep.
        filt_args : dict, optional
            Passed to the inner filter. The default is {}.

        Returns
        -------
        None.
        """
        if self._update_has_been_called:
            # Birth Track Table
            birth_tab = self._gen_birth_tab(timestep)[0]
        else:
            birth_tab = []
            warnings.warn("Joint GLMB should call predict and correct simultaneously")
        self._update_has_been_called = False

        # Survival Track Table
        surv_tab = self._gen_surv_tab(timestep, filt_args)

        # Prediction Track Table

        self._track_tab = birth_tab + surv_tab

    def _unique_faster(self, keys):
        difference = np.diff(np.append(keys, np.nan), n=1, axis=0)
        keyind = np.not_equal(difference, 0)
        mindices = (keys[0][np.where(keyind)]).astype(int)
        return mindices

    def _calc_avg_prob_surv_death(self):
        avg_surv = np.zeros(len(self.birth_terms) + self._old_track_tab_len)
        for ii in range(0, avg_surv.shape[0]):
            if ii <= len(self.birth_terms) - 1:
                avg_surv[ii] = self.birth_terms[ii][1]
            else:
                avg_surv[ii] = self.prob_survive
        # avg_surv = np.array([avg_surv]).T
        avg_death = 1 - avg_surv
        return avg_surv, avg_death

    def _calc_avg_prob_det_mdet(self):
        avg_detect = self.prob_detection * np.ones(len(self._track_tab))
        # avg_detect = np.array([avg_detect]).T
        avg_miss = 1 - avg_detect
        return avg_detect, avg_miss

    def _gen_cor_tab(self, num_meas, meas, timestep, filt_args):
        num_pred = len(self._track_tab)
        up_tab = [None] * (num_meas + 1) * num_pred

        for ii, track in enumerate(self._track_tab):
            up_tab[ii] = self._TabEntry()
            up_tab[ii].setup(track)
            up_tab[ii].meas_assoc_hist.append(None)
        # measurement updated tracks
        all_cost_m = np.zeros((num_pred, num_meas))
        # for emm, z in enumerate(meas):
        for ii, ent in enumerate(self._track_tab):
            for emm, z in enumerate(meas):

                num_meas = len(z)
                meas_d = z[0].shape[0]
                z_array = np.array(z).reshape((num_meas, meas_d)).transpose()

                s_to_ii = num_pred * emm + ii + num_pred
                (up_tab[s_to_ii], cost) = self._correct_track_tab_entry(
                    z_array, ent, timestep, filt_args
                )

                # update association history with current measurement index
                if up_tab[s_to_ii] is not None:
                    up_tab[s_to_ii].meas_assoc_hist.append(emm)
                all_cost_m[ii, emm] = cost
        return up_tab, all_cost_m

    def _gen_cor_hyps(
        self,
        num_meas,
        avg_prob_detect,
        avg_prob_miss_detect,
        avg_prob_surv,
        avg_prob_death,
        all_cost_m,
    ):
        # Define clutter
        clutter = self.clutter_rate * self.clutter_den
        # clutter = self.clutter_den

        # Joint Cost Matrix
        joint_cost = np.concatenate(
            [
                np.diag(avg_prob_death.ravel()),
                np.diag(avg_prob_surv.ravel() * avg_prob_miss_detect.ravel()),
            ],
            axis=1,
        )

        other_jc_terms = (
            np.tile((avg_prob_surv * avg_prob_detect).reshape((-1, 1)), (1, num_meas))
            * all_cost_m
            / (clutter)
        )

        # Full joint cost matrix
        joint_cost = np.append(joint_cost, other_jc_terms, axis=1)

        # Gated Measurement index matrix
        gate_meas_indices = np.zeros((len(self._track_tab), num_meas))
        for ii in range(0, len(self._track_tab)):
            for jj in range(0, len(self._track_tab[ii].gatemeas)):
                gate_meas_indices[ii][jj] = self._track_tab[ii].gatemeas[jj]
        gate_meas_indc = gate_meas_indices >= 0

        # Component updates
        ss_w = 0
        up_hyp = []
        for p_hyp in self._hypotheses:
            ss_w += np.sqrt(p_hyp.assoc_prob)
        for p_hyp in self._hypotheses:
            cpreds = len(self._track_tab)
            num_births = len(self.birth_terms)
            num_exists = len(p_hyp.track_set)
            num_tracks = num_births + num_exists

            # Hypothesis index masking
            tindices = np.concatenate(
                (np.arange(0, num_births), num_births + np.array(p_hyp.track_set))
            ).astype(int)
            lselmask = np.zeros((len(self._track_tab), num_meas), dtype="bool")
            lselmask[tindices,] = gate_meas_indc[tindices,]

            keys = np.array([np.sort(gate_meas_indices[lselmask])])
            mindices = self._unique_faster(keys)

            comb_tind_cpred = np.append(
                np.append(tindices, cpreds + tindices), [2 * cpreds + mindices]
            )
            # print(joint_cost.shape)
            # print(tindices)
            # print(comb_tind_cpred)
            cost_m = joint_cost[tindices][:, comb_tind_cpred]
            # print(cost_m.shape)
            # cost_m = np.zeros((len(tindices), len(comb_tind_cpred)))
            # cmi = 0
            # for ind in tindices:
            #     cost_m[cmi, :] = joint_cost[ind, comb_tind_cpred]
            #     cmi = cmi + 1
            with warnings.catch_warnings():
                warnings.simplefilter("ignore", RuntimeWarning)
                neg_log = -np.log(cost_m)

            m = np.round(self.req_upd * np.sqrt(p_hyp.assoc_prob) / ss_w)
            m = int(m.item()) + 1

            # Gibbs Sampler
            [assigns, costs] = gibbs(neg_log, m, rng=self._rng)

            # Process unique assighnments from gibbs sampler
            assigns[assigns < num_tracks] = -np.inf
            for ii in range(np.shape(assigns)[0]):
                if len(np.shape(assigns)) < 2:
                    if assigns[ii] >= num_tracks and assigns[ii] < 2 * num_tracks:
                        assigns[ii] = -1
                else:
                    for jj in range(np.shape(assigns)[1]):
                        if (
                            assigns[ii][jj] >= num_tracks
                            and assigns[ii][jj] < 2 * num_tracks
                        ):
                            assigns[ii][jj] = -1
            assigns[assigns >= 2 * num_tracks] -= 2 * num_tracks
            if assigns[assigns >= 0].size != 0:
                assigns[assigns >= 0] = mindices[
                    assigns[assigns >= 0].astype(int)[
                        assigns[assigns >= 0].astype(int) >= 0
                    ]
                ]
            # Assign updated hypotheses from gibbs sampler
            for c, cst in enumerate(costs.flatten()):
                update_hyp_cmp_temp = assigns[c,]
                update_hyp_cmp_idx = cpreds * (update_hyp_cmp_temp + 1) + np.append(
                    np.array([np.arange(0, num_births)]),
                    num_births + np.array([p_hyp.track_set]),
                )
                new_hyp = self._HypothesisHelper()
                new_hyp.assoc_prob = (
                    -self.clutter_rate
                    + num_meas * np.log(clutter)
                    + np.log(p_hyp.assoc_prob)
                    - cst
                )
                new_hyp.track_set = update_hyp_cmp_idx[update_hyp_cmp_idx >= 0].astype(
                    int
                )
                up_hyp.append(new_hyp)
        lse = log_sum_exp([x.assoc_prob for x in up_hyp])

        for ii in range(0, len(up_hyp)):
            up_hyp[ii].assoc_prob = np.exp(up_hyp[ii].assoc_prob - lse)
        return up_hyp

    def correct(self, timestep, meas_in, filt_args={}):
        """Correction step of the JGLMB filter.

        This corrects the hypotheses based on the measurements and gates the
        measurements according to the class settings. It also updates the
        cardinality distribution. Because this calls the inner filter's correct
        function, the keyword arguments must contain any information needed by
        that function.

        Parameters
        ----------
        timestep: float
            Current timestep.
        meas_in : list
            List of Nm x 1 numpy arrays each representing a measuremnt.
        filt_args : dict, optional
            keyword arguments to pass to the inner filters correct function.
            The default is {}.

        Todo
        ----
            Fix the measurement gating

        Returns
        -------
        None
        """

        meas = self._clustering_obj.cluster(meas_in)

        # gating by tracks
        if self.gating_on:
            RuntimeError("Gating not implemented yet. PLEASE TURN OFF GATING")
            # for ent in self._track_tab:
            #     ent.gatemeas = self._gate_meas(meas, ent.probDensity.means,
            #                                     ent.probDensity.covariances)
        else:
            for ent in self._track_tab:
                ent.gatemeas = np.arange(0, len(meas))
        # Pre-calculation of average survival/death probabilities
        avg_prob_surv, avg_prob_death = self._calc_avg_prob_surv_death()

        # Pre-calculation of average detection/missed probabilities
        avg_prob_detect, avg_prob_miss_detect = self._calc_avg_prob_det_mdet()

        if self.save_measurements:
            self._meas_tab.append(deepcopy(meas))
        num_meas = len(meas)

        # missed detection tracks
        [up_tab, all_cost_m] = self._gen_cor_tab(num_meas, meas, timestep, filt_args)

        up_hyp = self._gen_cor_hyps(
            num_meas,
            avg_prob_detect,
            avg_prob_miss_detect,
            avg_prob_surv,
            avg_prob_death,
            all_cost_m,
        )

        self._track_tab = up_tab
        self._hypotheses = up_hyp
        self._card_dist = self._calc_card_dist(self._hypotheses)
        self._clean_predictions()
        self._clean_updates()
        self._update_has_been_called = True
        self._old_track_tab_len = len(self._track_tab)








