import gncpy.filters
import numpy as np
import numpy.linalg as la
import numpy.random as rnd
import matplotlib.pyplot as plt
from typing import Iterable
from matplotlib.patches import Ellipse
import matplotlib.animation as animation
import abc
from copy import deepcopy
import warnings
import itertools

from carbs.utilities.graphs import (
    k_shortest,
    murty_m_best,
    murty_m_best_all_meas_assigned,
)
from carbs.utilities.sampling import gibbs, mm_gibbs

from gncpy.math import log_sum_exp, get_elem_sym_fnc
import gncpy.plotting as pltUtil
import gncpy.filters as gfilts
import gncpy.errors as gerr

import serums.models as smodels
from serums.enums import SingleObjectDistance
from serums.distances import calculate_ospa, calculate_ospa2, calculate_gospa



### MIGHT HAVE TO CHANGE IMPORTS BELOW, AND THEN CHANGE THEIR NAMES IN THE CLASS?? Depends if we do import serums.models or import GGIWMixture ###

from carbs.swarm_estimator.tracker import RandomFiniteSetBase
from carbs.extended_targets.GGIW_Serums_Models import GGIWMixture
from carbs.extended_targets.GGIW_Serums_Models import GGIW 

class GGIW_PHD(RandomFiniteSetBase):
    """Implements the Probability Hypothesis Density filter for the Gamma Gaussian Inverse Wishart distribution.

    The kwargs in the constructor are passed through to the parent constructor.

    Notes
    -----
    The filter implementation is based on :cite:`Vo2006_TheGaussianMixtureProbabilityHypothesisDensityFilter`

    Attributes
    ----------
    gating_on : bool
        flag indicating if measurement gating should be performed. The
        default is False.
    inv_chi2_gate : float
        threshold for the chi squared test in the measurement gating. The
        default is 0.
    extract_threshold : float
        threshold for extracting the state. The default is 0.5.
    prune_threshold : float
        threshold for removing hypotheses. The default is 10**-5.
    merge_threshold : float
        threshold for merging hypotheses. The default is 4.
    max_terms : int
        max number of gaussians to use. The default is 100.

    """

    def __init__(
        self,
        clustering_obj,
        gating_on=False,
        inv_chi2_gate=0,
        extract_threshold=0.5,
        prune_threshold=1e-5,
        merge_threshold=4,
        max_terms=100,
        partition_thresh = 1,
        **kwargs,
    ):
        self.gating_on = gating_on
        self.inv_chi2_gate = inv_chi2_gate
        self.extract_threshold = extract_threshold
        self.prune_threshold = prune_threshold
        self.merge_threshold = merge_threshold
        self.max_terms = max_terms
        self.partition_thresh = partition_thresh

        if clustering_obj is None:
            raise("Please choose a clustering_obj. ")
        else:
            self._clustering_obj = clustering_obj

        self._Mixture = GGIWMixture()


        super().__init__(**kwargs)

    def save_filter_state(self):
        """Saves filter variables so they can be restored later."""
        filt_state = super().save_filter_state()

        raise RuntimeError("Not implmented yet")
        return filt_state

    def load_filter_state(self, filt_state):
        """Initializes filter using saved filter state.

        Attributes
        ----------
        filt_state : dict
            Dictionary generated by :meth:`save_filter_state`.
        """
        super().load_filter_state(filt_state)

        raise RuntimeError("Not implmented yet")

    @property
    def states(self):
        """Read only list of extracted states.

        This is a list with 1 element per timestep, and each element is a list
        of the best states extracted at that timestep. The order of each
        element corresponds to the label order.
        """
        if len(self._states) > 0:
            return self._states[-1]
        else:
            return []

    @property
    def covariances(self):
        """Read only list of extracted covariances.

        This is a list with 1 element per timestep, and each element is a list
        of the best covariances extracted at that timestep. The order of each
        element corresponds to the state order.

        Warns
        -----
            RuntimeWarning
                If the class is not saving the covariances, and returns an
                empty list
        """
        if not self.save_covs:
            warnings.warn("Not saving covariances")
            return []
        if len(self._covs) > 0:
            return self._covs[-1]
        else:
            return []

    @property
    def cardinality(self):
        """Read only cardinality of the RFS."""
        if len(self._Mixture) == 0:
            return 0
        else:
            return len(self._Mixture[-1])

    # def _gen_spawned_targets(self, Mixture):
    #     if self.spawn_cov is not None and self.spawn_weight is not None:
    #         gauss_list = [
    #             smodels.Gaussian(mean=m.copy(), covariance=self.spawn_cov.copy())
    #             for m in Mixture.means
    #         ]
    #         return smodels.GaussianMixture(
    #             distributions=gauss_list,
    #             weights=[self.spawn_weight for ii in range(len(gauss_list))],
    #         )
    #     else:
    #         raise RuntimeError(
    #             "self.spawn_cov and self.spawn_weight must be specified."
    #         )

    def predict(self, timestep, filt_args={}):
        """Prediction step of the PHD filter.

        This predicts new hypothesis, and propogates them to the next time
        step. It also updates the cardinality distribution. Because this calls
        the inner filter's predict function, the keyword arguments must contain
        any information needed by that function.


        Parameters
        ----------
        timestep: float
            current timestep
        filt_args : dict, optional
            Passed to the inner filter. The default is {}.

        Returns
        -------
        None.

        """

        if self.enable_spawning:
            print("Warning: Spawning not implemented yet. \n\n")

        # if self.enable_spawning:
        #     spawn_mix = self._gen_spawned_targets(self._Mixture)

        self._Mixture = self._predict_prob_density(timestep, self._Mixture, filt_args)

        # if self.enable_spawning:
        #     self._Mixture.add_components(
        #         spawn_mix.means, spawn_mix.covariances, spawn_mix.weights
        #     )

        for mix in self.birth_terms:
            obj = mix[1]
            weight = mix[0] 
            self._Mixture.add_components(obj.alpha, obj.beta, obj.mean, obj.covariance, obj.IWdof, obj.IWshape, weight)

    def _predict_prob_density(self, timestep, probDensity, filt_args):

        weights = [self.prob_survive * x for x in probDensity.weights.copy()] 
        n_terms = len(weights)
        NewMixture = GGIWMixture() 
        for ii, _ in enumerate(probDensity._distributions):

            cur_probDensity = probDensity._distributions[ii]

            pred_probDensity = self.filter.predict(timestep,cur_probDensity, filt_args)

            NewMixture.add_components(pred_probDensity.alpha, pred_probDensity.beta, pred_probDensity.mean, pred_probDensity.covariance, pred_probDensity.IWdof, pred_probDensity.IWshape, weights=weights[ii])            
            
        return NewMixture 

    def correct(
        self, timestep, meas_in, meas_mat_args={}, est_meas_args={}, filt_args={}
    ):

        meas = deepcopy(meas_in)

        if self.gating_on:
            print("Warning: gating not implemented yet. \n\n")
            # meas = self._gate_meas(
            #     meas,
            #     self._Mixture.means,
            #     self._Mixture.covariances,
            #     meas_mat_args,
            #     est_meas_args,
            # )

        self._meas_tab.append(meas)   # Keeps track of measurements for plotting purposes

        # Partition measurements
        parted_meas = self._clustering_obj.cluster(meas)

        Mix = deepcopy(self._Mixture)
        Mix.weights = [self.prob_miss_detection * x for x in Mix.weights]

        UpdMix = self._correct_prob_density(timestep, parted_meas, self._Mixture, filt_args) 
        UpdMix.add_components(Mix.alphas, Mix.betas, Mix.means, Mix.covariances, Mix.IWdofs, Mix.IWshapes, Mix.weights) 

        self._Mixture = UpdMix

    def _correct_prob_density(self, timestep, parted_meas, probDensity, filt_args):
        # means = []
        # covariances = []

        if parted_meas:

            weights = []

            Mix_temp = GGIWMixture()

            det_weights = [self.prob_detection * x for x in probDensity.weights]

            for z in parted_meas: 

                w_lst = []

                # Convert the measurement set from list of len N of Dx1 arrays to 
                # an DxN array 
                num_meas = len(z)
                meas_d = z[0].shape[0]
                z_array = np.array(z).reshape((num_meas, meas_d)).transpose()

                for jj in range(0, len(probDensity)):
                    cur_dist = probDensity[jj] 
                    (upd_dist, qz) = self.filter.correct(timestep, z_array, cur_dist, **filt_args) 
                    w = qz * det_weights[jj]

                    Mix_temp.add_components(upd_dist.alpha, upd_dist.beta, upd_dist.mean, upd_dist.covariance, upd_dist.IWdof, upd_dist.IWshape, w)            

                    w_lst.append(w)

                weights.extend(
                    [x / (self.clutter_rate * self.clutter_den + sum(w_lst)) for x in w_lst]
                )

            Mix_temp.weights = weights

            return Mix_temp
        else:
            return probDensity

    def _prune(self):
        """Removes hypotheses below a threshold.

        This should be called once per time step after the correction and
        before the state extraction.
        """
        inds = np.where(np.asarray(self._Mixture.weights) < self.prune_threshold)[0]
        self._Mixture.remove_components(inds.flatten().tolist())
        return inds

    def _merge(self):
            """Merges nearby hypotheses."""
            loop_inds = set(range(0, len(self._Mixture.means)))

            w_lst = []
            a_lst = []
            b_lst = []
            m_lst = []
            p_lst = []
            v_lst = []
            V_lst = []
            while len(loop_inds) > 0:
                jj = int(np.argmax(self._Mixture.weights))
                comp_inds = []
                inv_cov = la.inv(self._Mixture.covariances[jj])
                for ii in loop_inds:
                    diff = self._Mixture.means[ii] - self._Mixture.means[jj]
                    val = diff.T @ inv_cov @ diff
                    if val <= self.merge_threshold:
                        comp_inds.append(ii)
                w_new = sum([self._Mixture.weights[ii] for ii in comp_inds])
                m_new = (
                    sum(
                        [
                            self._Mixture.weights[ii] * self._Mixture.means[ii]
                            for ii in comp_inds
                        ]
                    )
                    / w_new
                )
                p_new = (
                    sum(
                        [
                            self._Mixture.weights[ii] * self._Mixture.covariances[ii]
                            for ii in comp_inds
                        ]
                    )
                    / w_new
                )
                p_new = 0.5 * (p_new+p_new.T)
                a_new = (
                    sum(
                        [
                            self._Mixture.weights[ii] * self._Mixture.alphas[ii]
                            for ii in comp_inds
                        ]
                    )
                    / w_new
                )
                b_new = (
                    sum(
                        [
                            self._Mixture.weights[ii] * self._Mixture.betas[ii]
                            for ii in comp_inds
                        ]
                    )
                    / w_new
                )
                v_new = (
                    sum(
                        [
                            self._Mixture.weights[ii] * self._Mixture.IWdofs[ii]
                            for ii in comp_inds
                        ]
                    )
                    / w_new
                )
                V_new = (
                    sum(
                        [
                            self._Mixture.weights[ii] * self._Mixture.IWshapes[ii]
                            for ii in comp_inds
                        ]
                    )
                    / w_new
                )

                w_lst.append(w_new)
                m_lst.append(m_new)
                p_lst.append(p_new)
                a_lst.append(a_new)
                b_lst.append(b_new)
                v_lst.append(v_new)
                V_lst.append(V_new)

                loop_inds = loop_inds.symmetric_difference(comp_inds)
                for ii in comp_inds:
                    self._Mixture.weights[ii] = -1
            # self._Mixture = smodels.GaussianMixture(
            #     means=m_lst, covariances=p_lst, weights=w_lst
            # )

            self._Mixture = GGIWMixture(alphas=a_lst,betas=b_lst,means=m_lst,covariances=p_lst,IWdofs=v_lst,IWshapes=V_lst)
            self._Mixture.weights = w_lst



    def _cap(self):
        """Removes least likely hypotheses until a maximum number is reached.

        This should be called once per time step after pruning and
        before the state extraction.
        """
        if len(self._Mixture.weights) > self.max_terms:
            idx = np.argsort(self._Mixture.weights)
            w = sum(self._Mixture.weights)
            self._Mixture.remove_components(idx[0 : -self.max_terms])
            self._Mixture.weights = [
                x * (w / sum(self._Mixture.weights)) for x in self._Mixture.weights
            ]
            return idx[0 : -self.max_terms].tolist()
        return []

    def extract_states(self):
        """Extracts the best state estimates.

        This extracts the best states from the distribution. It should be
        called once per time step after the correction function.
        """
        inds = np.where(np.asarray(self._Mixture.weights) >= self.extract_threshold)
        inds = np.ndarray.flatten(inds[0])
        s_lst = []
        c_lst = []
        for jj in inds:
            jj = int(jj)
            num_reps = round(self._Mixture.weights[jj])
            s_lst.extend([self._Mixture.means[jj]] * num_reps)
            if self.save_covs:
                c_lst.extend([self._Mixture.covariances[jj]] * num_reps)
        self._states.append(s_lst)
        if self.save_covs:
            self._covs.append(c_lst)

    def extract_mixture(self): 
        inds = np.where(np.asarray(self._Mixture.weights) >= self.extract_threshold)[0]

        temp = GGIWMixture() 

        for ii in inds:
            mix = self._Mixture[int(ii)]
            temp.add_components(
                mix.alpha,
                mix.beta,
                mix.mean,
                mix.covariance,
                mix.IWdof,
                mix.IWshape,
                self._Mixture.weights[ii]
            )

        return temp

    def cleanup(
        self,
        enable_prune=True,
        enable_cap=True,
        enable_merge=True,
        enable_extract=True,
        extract_kwargs=None,
    ):
        """Performs the cleanup step of the filter.

        This can prune, cap, and extract states. It must be called once per
        timestep. If this is called with `enable_extract` set to true then
        the extract states method does not need to be called separately. It is
        recommended to call this function instead of
        :meth:`carbs.swarm_estimator.tracker.GeneralizedLabeledMultiBernoulli.extract_states`
        directly.

        Parameters
        ----------
        enable_prune : bool, optional
            Flag indicating if prunning should be performed. The default is True.
        enable_cap : bool, optional
            Flag indicating if capping should be performed. The default is True.
        enable_merge : bool, optional
            Flag indicating if merging should be performed. The default is True.
        enable_extract : bool, optional
            Flag indicating if state extraction should be performed. The default is True.
        extract_kwargs : dict, optional
            Extra arguments to pass to the extract function.
        """
        if enable_prune:
            self._prune()
        if enable_merge:
            self._merge()
        if enable_cap:
            self._cap()
        if enable_extract:
            if extract_kwargs is None:
                extract_kwargs = {}
            self.extract_states(**extract_kwargs)

    def __ani_state_plotting(
        self,
        f_hndl,
        tt,
        states,
        show_sig,
        plt_inds,
        sig_bnd,
        color,
        marker,
        state_lbl,
        added_sig_lbl,
        added_state_lbl,
        scat=None,
    ):
        if scat is None:
            if not added_state_lbl:
                scat = f_hndl.axes[0].scatter(
                    [], [], color=color, edgecolors=(0, 0, 0), marker=marker
                )
            else:
                scat = f_hndl.axes[0].scatter(
                    [],
                    [],
                    color=color,
                    edgecolors=(0, 0, 0),
                    marker=marker,
                    label=state_lbl,
                )
        if len(states) == 0:
            return scat
        x = np.concatenate(states, axis=1)
        if show_sig:
            sigs = [None] * len(states)
            for ii, cov in enumerate(self._covs[tt]):
                sig = np.zeros((2, 2))
                sig[0, 0] = cov[plt_inds[0], plt_inds[0]]
                sig[0, 1] = cov[plt_inds[0], plt_inds[1]]
                sig[1, 0] = cov[plt_inds[1], plt_inds[0]]
                sig[1, 1] = cov[plt_inds[1], plt_inds[1]]
                sigs[ii] = sig
            # plot
            for ii, sig in enumerate(sigs):
                if sig is None:
                    continue
                w, h, a = pltUtil.calc_error_ellipse(sig, sig_bnd)
                if not added_sig_lbl:
                    s = r"${}\sigma$ Error Ellipses".format(sig_bnd)
                    e = Ellipse(
                        xy=x[plt_inds, ii],
                        width=w,
                        height=h,
                        angle=a,
                        zorder=-10000,
                        animated=True,
                        label=s,
                    )
                else:
                    e = Ellipse(
                        xy=x[plt_inds, ii],
                        width=w,
                        height=h,
                        angle=a,
                        zorder=-10000,
                        animated=True,
                    )
                e.set_clip_box(f_hndl.axes[0].bbox)
                e.set_alpha(0.15)
                e.set_facecolor(color)
                f_hndl.axes[0].add_patch(e)
        scat.set_offsets(x[plt_inds[0:2], :].T)
        return scat

    def plot_states(
        self,
        plt_inds,
        state_lbl="States",
        ttl=None,
        state_color=None,
        x_lbl=None,
        y_lbl=None,
        **kwargs,
    ):
        """Plots the best estimate for the states.

        This assumes that the states have been extracted. It's designed to plot
        two of the state variables (typically x/y position). The error ellipses
        are calculated according to :cite:`Hoover1984_AlgorithmsforConfidenceCirclesandEllipses`

        Keyword arguments are processed with
        :meth:`gncpy.plotting.init_plotting_opts`. This function
        implements

            - f_hndl
            - true_states
            - sig_bnd
            - rng
            - meas_inds
            - lgnd_loc
            - marker

        Parameters
        ----------
        plt_inds : list
            List of indices in the state vector to plot
        state_lbl : string
            Value to appear in legend for the states. Only appears if the
            legend is shown
        ttl : string, optional
            Title for the plot, if None a default title is generated. The default
            is None.
        x_lbl : string
            Label for the x-axis.
        y_lbl : string
            Label for the y-axis.

        Returns
        -------
        Matplotlib figure
            Instance of the matplotlib figure used
        """
        opts = pltUtil.init_plotting_opts(**kwargs)
        f_hndl = opts["f_hndl"]
        true_states = opts["true_states"]
        sig_bnd = opts["sig_bnd"]
        rng = opts["rng"]
        meas_inds = opts["meas_inds"]
        lgnd_loc = opts["lgnd_loc"]
        marker = opts["marker"]
        if ttl is None:
            ttl = "State Estimates"
        if rng is None:
            rng = rnd.default_rng(1)
        if x_lbl is None:
            x_lbl = "x-position"
        if y_lbl is None:
            y_lbl = "y-position"
        plt_meas = meas_inds is not None
        show_sig = sig_bnd is not None and self.save_covs

        s_lst = deepcopy(self._states)
        x_dim = None

        if f_hndl is None:
            f_hndl = plt.figure()
            f_hndl.add_subplot(1, 1, 1)
        # get state dimension
        for states in s_lst:
            if len(states) > 0:
                x_dim = states[0].size
                break
        # get array of all state values for each label
        added_sig_lbl = False
        added_true_lbl = False
        added_state_lbl = False
        added_meas_lbl = False
        r = rng.random()
        b = rng.random()
        g = rng.random()
        if state_color is None:
            color = (r, g, b)
        else:
            color = state_color
        for tt, states in enumerate(s_lst):
            if len(states) == 0:
                continue
            x = np.concatenate(states, axis=1)
            if show_sig:
                sigs = [None] * len(states)
                for ii, cov in enumerate(self._covs[tt]):
                    sig = np.zeros((2, 2))
                    sig[0, 0] = cov[plt_inds[0], plt_inds[0]]
                    sig[0, 1] = cov[plt_inds[0], plt_inds[1]]
                    sig[1, 0] = cov[plt_inds[1], plt_inds[0]]
                    sig[1, 1] = cov[plt_inds[1], plt_inds[1]]
                    sigs[ii] = sig
                # plot
                for ii, sig in enumerate(sigs):
                    if sig is None:
                        continue
                    w, h, a = pltUtil.calc_error_ellipse(sig, sig_bnd)
                    if not added_sig_lbl:
                        s = r"${}\sigma$ Error Ellipses".format(sig_bnd)
                        e = Ellipse(
                            xy=x[plt_inds, ii],
                            width=w,
                            height=h,
                            angle=a,
                            zorder=-10000,
                            label=s,
                        )
                        added_sig_lbl = True
                    else:
                        e = Ellipse(
                            xy=x[plt_inds, ii],
                            width=w,
                            height=h,
                            angle=a,
                            zorder=-10000,
                        )
                    e.set_clip_box(f_hndl.axes[0].bbox)
                    e.set_alpha(0.15)
                    e.set_facecolor(color)
                    f_hndl.axes[0].add_patch(e)
            if not added_state_lbl:
                f_hndl.axes[0].scatter(
                    x[plt_inds[0], :],
                    x[plt_inds[1], :],
                    color=color,
                    edgecolors=(0, 0, 0),
                    marker=marker,
                    label=state_lbl,
                )
                added_state_lbl = True
            else:
                f_hndl.axes[0].scatter(
                    x[plt_inds[0], :],
                    x[plt_inds[1], :],
                    color=color,
                    edgecolors=(0, 0, 0),
                    marker=marker,
                )
        # if true states are available then plot them
        if true_states is not None:
            if x_dim is None:
                for states in true_states:
                    if len(states) > 0:
                        x_dim = states[0].size
                        break
            max_true = max([len(x) for x in true_states])
            x = np.nan * np.ones((x_dim, len(true_states), max_true))
            for tt, states in enumerate(true_states):
                for ii, state in enumerate(states):
                    x[:, [tt], ii] = state.copy()
            for ii in range(0, max_true):
                if not added_true_lbl:
                    f_hndl.axes[0].plot(
                        x[plt_inds[0], :, ii],
                        x[plt_inds[1], :, ii],
                        color="k",
                        marker=".",
                        label="True Trajectories",
                    )
                    added_true_lbl = True
                else:
                    f_hndl.axes[0].plot(
                        x[plt_inds[0], :, ii],
                        x[plt_inds[1], :, ii],
                        color="k",
                        marker=".",
                    )
        if plt_meas:
            meas_x = []
            meas_y = []
            for meas_tt in self._meas_tab:
                mx_ii = [m[meas_inds[0]].item() for m in meas_tt]
                my_ii = [m[meas_inds[1]].item() for m in meas_tt]
                meas_x.extend(mx_ii)
                meas_y.extend(my_ii)
            color = (128 / 255, 128 / 255, 128 / 255)
            meas_x = np.asarray(meas_x)
            meas_y = np.asarray(meas_y)
            if not added_meas_lbl:
                f_hndl.axes[0].scatter(
                    meas_x,
                    meas_y,
                    zorder=-1,
                    alpha=0.35,
                    color=color,
                    marker="^",
                    edgecolors=(0, 0, 0),
                    label="Measurements",
                )
            else:
                f_hndl.axes[0].scatter(
                    meas_x,
                    meas_y,
                    zorder=-1,
                    alpha=0.35,
                    color=color,
                    marker="^",
                    edgecolors=(0, 0, 0),
                )
        f_hndl.axes[0].grid(True)
        pltUtil.set_title_label(f_hndl, 0, opts, ttl=ttl, x_lbl=x_lbl, y_lbl=y_lbl)

        if lgnd_loc is not None:
            plt.legend(loc=lgnd_loc)
        plt.tight_layout()

        return f_hndl

    def animate_state_plot(
        self,
        plt_inds,
        state_lbl="States",
        state_color=None,
        interval=250,
        repeat=True,
        repeat_delay=1000,
        save_path=None,
        **kwargs,
    ):
        """Creates an animated plot of the states.

        Parameters
        ----------
        plt_inds : list
            indices of the state vector to plot.
        state_lbl : string, optional
            label for the states. The default is 'States'.
        state_color : tuple, optional
            3-tuple for rgb value. The default is None.
        interval : int, optional
            interval of the animation in ms. The default is 250.
        repeat : bool, optional
            flag indicating if the animation loops. The default is True.
        repeat_delay : int, optional
            delay between loops in ms. The default is 1000.
        save_path : string, optional
            file path and name to save the gif, does not save if not given.
            The default is None.
        **kwargs : dict, optional
            Standard plotting options for
            :meth:`gncpy.plotting.init_plotting_opts`. This function
            implements

                - f_hndl
                - sig_bnd
                - rng
                - meas_inds
                - lgnd_loc
                - marker

        Returns
        -------
        anim :
            handle to the animation.

        """
        opts = pltUtil.init_plotting_opts(**kwargs)
        f_hndl = opts["f_hndl"]
        sig_bnd = opts["sig_bnd"]
        rng = opts["rng"]
        meas_inds = opts["meas_inds"]
        lgnd_loc = opts["lgnd_loc"]
        marker = opts["marker"]

        plt_meas = meas_inds is not None
        show_sig = sig_bnd is not None and self.save_covs

        f_hndl.axes[0].grid(True)
        pltUtil.set_title_label(
            f_hndl,
            0,
            opts,
            ttl="State Estimates",
            x_lbl="x-position",
            y_lbl="y-position",
        )

        fr_number = f_hndl.axes[0].annotate(
            "0",
            (0, 1),
            xycoords="axes fraction",
            xytext=(10, -10),
            textcoords="offset points",
            ha="left",
            va="top",
            animated=False,
        )

        added_sig_lbl = False
        added_state_lbl = False
        added_meas_lbl = False
        r = rng.random()
        b = rng.random()
        g = rng.random()
        if state_color is None:
            s_color = (r, g, b)
        else:
            s_color = state_color
        state_scat = f_hndl.axes[0].scatter(
            [], [], color=s_color, edgecolors=(0, 0, 0), marker=marker, label=state_lbl
        )
        meas_scat = None
        if plt_meas:
            m_color = (128 / 255, 128 / 255, 128 / 255)

            if meas_scat is None:
                if not added_meas_lbl:
                    lbl = "Measurements"
                    meas_scat = f_hndl.axes[0].scatter(
                        [],
                        [],
                        zorder=-1,
                        alpha=0.35,
                        color=m_color,
                        marker="^",
                        edgecolors="k",
                        label=lbl,
                    )
                    added_meas_lbl = True
                else:
                    meas_scat = f_hndl.axes[0].scatter(
                        [],
                        [],
                        zorder=-1,
                        alpha=0.35,
                        color=m_color,
                        marker="^",
                        edgecolors="k",
                    )

        def update(tt, *fargs):
            nonlocal added_sig_lbl
            nonlocal added_state_lbl
            nonlocal added_meas_lbl
            nonlocal state_scat
            nonlocal meas_scat
            nonlocal fr_number

            fr_number.set_text("Timestep: {j}".format(j=tt))

            states = self._states[tt]
            state_scat = self.__ani_state_plotting(
                f_hndl,
                tt,
                states,
                show_sig,
                plt_inds,
                sig_bnd,
                s_color,
                marker,
                state_lbl,
                added_sig_lbl,
                added_state_lbl,
                scat=state_scat,
            )
            added_sig_lbl = True
            added_state_lbl = True

            if plt_meas:
                meas_tt = self._meas_tab[tt]

                meas_x = [m[meas_inds[0]].item() for m in meas_tt]
                meas_y = [m[meas_inds[1]].item() for m in meas_tt]

                meas_x = np.asarray(meas_x)
                meas_y = np.asarray(meas_y)
                meas_scat.set_offsets(np.array([meas_x, meas_y]).T)

        # plt.figure(f_hndl.number)
        anim = animation.FuncAnimation(
            f_hndl,
            update,
            frames=len(self._states),
            interval=interval,
            repeat_delay=repeat_delay,
            repeat=repeat,
        )

        if lgnd_loc is not None:
            plt.legend(loc=lgnd_loc)
        if save_path is not None:
            writer = animation.PillowWriter(fps=30)
            anim.save(save_path, writer=writer)
        return anim